package secm_img_sim_client;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.Charset;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Calendar;
import java.util.LinkedList;
import java.util.ListIterator;
import java.util.Scanner;

/**
 * Collection of methods for simulating secm images and connecting to a server for data processing of results.
 * @author Nathaniel Leslie
 */
public class SecmImgSimMain {

    /**
     * Dummy method for an autogenerated run method for COMSOL responsible for simulating an SECM image
     * @param L
     * @param xpositions
     * @param ypositions 
     */
    private static Model run(double a, double Rg, double D, double L, double[] xpositions, double[] ypositions){
        double[] data = new double[]{
            2.961349523707295E-11,
            2.9759165579137625E-11,
            3.113409413759452E-11,
            3.9948202563772906E-11,
            5.547861546411381E-11,
            6.066082017877612E-11,
            6.170878271140456E-11,
            6.210256176777017E-11,
            6.215263776910492E-11,
            6.215733984352189E-11};
        File of = new File(FILE_PATH_DATA);
        int len = xpositions.length * ypositions.length;
        try{
            PrintWriter pw = new PrintWriter(of);
            for(int i = 0; i < len; i++){
                int indx = i % (data.length - 1);
                pw.println(data[indx]);
            }
            pw.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        //Model model = ModelUtil.create("Model");
        //return model;
        return new Model();
    }
    
    /**
     * Dummy method for an autogenerated run method for COMSOL responsible for simulating a k-i curve
     * @param L
     * @param xposition
     * @param yposition 
     */
    private static Model runk(double a, double Rg, double D, double L, double xposition, double yposition, double[] ks){
        double[] data = new double[]{
            2.961349523707295E-11,
            2.9759165579137625E-11,
            3.113409413759452E-11,
            3.9948202563772906E-11,
            5.547861546411381E-11,
            6.066082017877612E-11,
            6.170878271140456E-11,
            6.210256176777017E-11,
            6.215263776910492E-11,
            6.215733984352189E-11};
        
        File of = new File(FILE_PATH_DATA);
        try{
            PrintWriter pw = new PrintWriter(of);
            for(int i = 0; i < ks.length; i++){
                pw.println(data[i]);
            }
            pw.close();
        }
        catch(Exception e){
            
        }
        
        //Model model = ModelUtil.create("Model");
        //return model;
        return new Model();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args){
        
        double L = 1.0; // Tip to substrate distance in a
        double D = 6.7E-10; //Diffusion coefficient in [m^2/s]
        double a = 2.35E-6; //ME radius in [m]
        double Rg = 1.87; // glass radius in a
        
        /*
        https://docs.oracle.com/javase/tutorial/networking/sockets/readingWriting.html
        https://docs.oracle.com/javase/tutorial/networking/sockets/clientServer.html
        https://docs.oracle.com/javase/8/docs/api/java/net/Socket.html
        */
        Socket deconv_service_socket = null;
        OutputStream sender = null;
        InputStream receiver = null;
        
        try{
            deconv_service_socket = new Socket(HOST, PORT);
            sender = deconv_service_socket.getOutputStream();
            receiver = deconv_service_socket.getInputStream();
            
            //read secm image
            String filepath = "C:\\Users\\Malak\\Documents\\NLeslie\\00_DECONV_SERVER\\Testenv1_Files\\Test_Pattern_1.csv";
//            String filepath = "Test_Pattern_1.csv";
            readInstructionFile(filepath);
            
            //simulate kcurves
            simulateKCurve(a, Rg, D, L, true);
            
            //initialize kimage
            initializeKappaImage();
            writeReactivityFile(img_x_coordinates, img_y_coordinates, img_kappas);
            //PUT kcurve
            putKCurve(sender, receiver, ki_logks, ki_currents);
            
            //PUT kimage
            putKImage(sender, receiver, img_x_coordinates, img_y_coordinates, img_kappas);
            
            //PUT true image
            putTrueSecmImage(sender, receiver, img_x_coordinates, img_y_coordinates, img_true);
            
            //LOOP:
            
                //simulate SECM image
                simulateImage(a, Rg, D, L);

                //POST SECM image [x]
                postSecmImage(sender, receiver, sim_x_coordinates, sim_y_coordinates, img_sim);
            
            //:END LOOP
            
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            if(sender != null){
                try{
                    sender.close();
                }catch(Exception e){
                    
                }
            }
            if(receiver != null){
                try{
                    receiver.close();
                }catch(IOException e){
                    
                }
            }
            if(deconv_service_socket != null){
                try{
                    deconv_service_socket.close();
                }catch(IOException e){
                    
                }
            }
        }
        
    }
    
    /**
     * 
     * @param list
     * @param value 
     */
    private static void addInOrder(LinkedList<Double> list, double value){
        if(!list.isEmpty()){
            ListIterator<Double> list_li = list.listIterator();
            boolean placed = false;
            while(list_li.hasNext() && !placed){
                double current = list_li.next();
                if(tolerantEquals(current, value, false)){
                    placed = true;
                }
                else if (current > value){
                    list_li.previous();
                    list_li.add(value);
                    placed = true;
                }
            }
            if(!placed){
                list_li.add(value);
            }
        }
        else{
            list.add(value);
        }
    }
    
    /**
     * Converts a scaled current signal to the approximate logk value that may have generated it.
     * This serves as an inverse for {@link #logKappaToCurrent(double)}.
     * Newton's method is used to approximate this logk value.
     * @param current The scaled current as a value between 0 and 1.
     * @return the logk that will result in current when used as an argument for {@link #logKappaToCurrent(double)}.
     */
    static double currentToLogKappa(double current){
        int len_m1 = ki_currents.length - 1;
        if(ki_currents[0] < ki_currents[len_m1]){//ascending order
            if(current > ki_currents[0] && current < ki_currents[len_m1]){
                int lower = findLower(ki_currents, current);
                double kappa_lower = ki_logks[lower];
                double kappa_upper = ki_logks[lower + 1];
                double current_lower = ki_currents[lower];
                double current_upper = ki_currents[lower + 1];

                double current_distance = current_upper - current_lower;
                double fact_lower = (current_upper - current)/current_distance;
                double fact_upper = 1.0-fact_lower;
                return kappa_lower*fact_lower + kappa_upper*fact_upper;
            }
            else if(current <= ki_currents[0]){
                return ki_logks[0];
            }
            else{
                return ki_logks[len_m1];
            }
        }
        else{//descending order
            if(current < ki_currents[0] && current > ki_currents[len_m1]){
                int upper = findGreater(ki_currents, current);
                double kappa_upper = ki_logks[upper];
                double kappa_lower = ki_logks[upper + 1];
                double current_upper = ki_currents[upper];
                double current_lower = ki_currents[upper + 1];

                double current_distance = current_upper - current_lower;
                double fact_lower = (current_upper - current)/current_distance;
                double fact_upper = 1.0-fact_lower;
                return kappa_lower*fact_lower + kappa_upper*fact_upper;
            }
            else if(current <= ki_currents[len_m1]){
                return ki_logks[len_m1];
            }
            else{
                return ki_logks[0];
            }
        }
    }
    
    /**
     * Decodes the bytes representing a k-image from the server and puts the data into img_x_coordinates, img_y_coordinates, img_kappas
     * @param encoded_image
     * @throws IOException 
     */
    private static void decodeIncomingKImage(byte[] encoded_image) throws IOException{
        String crlf = "\r\n";
        byte[] crlf_data = crlf.getBytes(CHARSET);
        byte[] crlf_detection_buffer = new byte[crlf_data.length];
        int endx = 0;
        //Scan until the CRLF
        for(int i = 0; i < encoded_image.length; i++){
            for(int cdb = 0; cdb < crlf_data.length - 1; cdb ++){
                crlf_detection_buffer[cdb] = crlf_detection_buffer[cdb + 1];
            }
            crlf_detection_buffer[crlf_data.length - 1] = encoded_image[i];
            boolean line_end = true;
            for(int cdb = 0; cdb < crlf_data.length; cdb++){
                if(crlf_detection_buffer[cdb] != crlf_data[cdb]){
                    line_end = false;
                    break;
                }
            }
            if(line_end){
                endx = i;
                break;
            }
        }
        if(endx == 0){
            throw new IOException("No CRLF encountered when decoding image.");
        }
        
        crlf_detection_buffer = new byte[crlf_data.length];
        int endy = endx;
        //scan until second CRLF
        for(int i = endx; i < encoded_image.length; i++){
            for(int cdb = 0; cdb < crlf_data.length - 1; cdb ++){
                crlf_detection_buffer[cdb] = crlf_detection_buffer[cdb + 1];
            }
            crlf_detection_buffer[crlf_data.length - 1] = encoded_image[i];
            boolean line_end = true;
            for(int cdb = 0; cdb < crlf_data.length; cdb++){
                if(crlf_detection_buffer[cdb] != crlf_data[cdb]){
                    line_end = false;
                    break;
                }
            }
            if(line_end){
                endy = i;
                break;
            }
        }
        if(endy == endx){
            throw new IOException("No CRLF encountered beyond the first line when decoding image.");
        }
        //parse-out the x and y dimensions of the image
        endx ++;
        endy ++;
        byte[] length_line_x_bytes = new byte[endx];
        byte[] length_line_y_bytes = new byte[endy - endx];
        System.arraycopy(encoded_image, 0, length_line_x_bytes, 0, endx);
        System.arraycopy(encoded_image, endx, length_line_y_bytes, 0, endy - endx);
        String length_line_x = new String(length_line_x_bytes, CHARSET);
        String length_line_y = new String(length_line_y_bytes, CHARSET);
        if(!length_line_x.startsWith("xlen: ")){
            throw new IOException("Image x-size line did not start as expected: " + length_line_x);
        }
        if(!length_line_y.startsWith("ylen: ")){
            throw new IOException("Image y-size line did not start as expected: " + length_line_y);
        }
        String length_part_x = length_line_x.substring(6, length_line_x.length() - crlf_data.length);
        String length_part_y = length_line_y.substring(6, length_line_y.length() - crlf_data.length);
        int xlen = Integer.parseInt(length_part_x);
        int ylen = Integer.parseInt(length_part_y);
        //check expected size against actual size
        //int expected_encoded_length = xlen*8 + ylen*8 + xlen*ylen*8 + endx + endy + CRLF.length*3;
        int expected_encoded_length = xlen*8 + ylen*8 + xlen*ylen*8 + endy + crlf_data.length*3;
        int actual_encoded_length = encoded_image.length;
        if(expected_encoded_length != actual_encoded_length){
            throw new IOException(String.format("Expected content length of %d bytes. Received: %d", expected_encoded_length, actual_encoded_length));
        }
        
        byte[] byte_data_x = new byte[xlen*8];
        byte[] byte_data_y = new byte[ylen*8];
        byte[] byte_data_image = new byte[xlen*ylen*8];
        System.arraycopy(encoded_image, endy, byte_data_x, 0, xlen*8);
        System.arraycopy(encoded_image, endy + xlen*8 + crlf_data.length, byte_data_y, 0, ylen*8);
        System.arraycopy(encoded_image, endy + xlen*8 + ylen*8 + crlf_data.length*2, byte_data_image, 0, xlen*ylen*8);
        
        //convert byte arrays to doubles.
        ByteBuffer x_bb = ByteBuffer.wrap(byte_data_x).order(ENDIANNESS);
        ByteBuffer y_bb = ByteBuffer.wrap(byte_data_y).order(ENDIANNESS);
        ByteBuffer img_bb = ByteBuffer.wrap(byte_data_image).order(ENDIANNESS);
        
        img_x_coordinates = new double[xlen];
        img_y_coordinates = new double[ylen];
        img_kappas = new double[xlen][ylen];
        
        for(int x = 0; x < xlen; x++){
            int xcontrib = x*ylen;
            img_x_coordinates[x] = x_bb.getDouble(x*8);
            for(int y = 0; y < ylen; y++){
                int indx = (xcontrib + y)*8;
                img_kappas[x][y] = img_bb.getDouble(indx);
            }
        }
        
        for(int y= 0; y < ylen; y++){
            img_y_coordinates[y] = y_bb.getDouble(y*8);
        }
    }
    
    /**
     * <p>Encodes a logk - current curve into a byte array for sending over a network connection.</p>
     * <p>Data is encoded according to the following format:</p>
     * <code><p>"len: %d\r\n"</p>
     * <p>[Binary data containing logks] + "\r\n"</p>
     * <p>[Binary data containing currents] + "\r\n"</p></code>
     * <p>Doubles are converted to bytes using {@link #ENDIANNESS} endianness</p>
     * <p></p>
     * @param logks a double array comprising the logk data
     * @param currents a double array comprising the current data
     * @return the logk - current encoded as a byte array
     */
    private static byte[] encodeCurve(double[] logks, double[] currents){
        /*
        "len: %d\r\n", len
        [Binary data containing logks] + "\r\n"
        [Binary data containing currents] + "\r\n"
        */
        int len = logks.length;
        String first_line = String.format("len: %d\r\n", len);
        String crlf = "\r\n";
        
        byte[] first_line_data = first_line.getBytes(CHARSET);
        byte[] crlf_data = crlf.getBytes(CHARSET);
        byte[] logk_data = new byte[len*8];
        byte[] current_data = new byte[len*8];
        
        ByteBuffer logk_bb = ByteBuffer.wrap(logk_data).order(ENDIANNESS);
        ByteBuffer current_bb = ByteBuffer.wrap(current_data).order(ENDIANNESS);
        
        for(int i = 0; i < logks.length; i++){
            logk_bb.putDouble(i*8, logks[i]);
            current_bb.putDouble(i*8, currents[i]);
        }
        
        //Append the data together
        int block_length = first_line_data.length + logk_data.length + current_data.length + 2*crlf_data.length;
        byte[] block_data = new byte[block_length];
        int running_length = 0;
        System.arraycopy(first_line_data, 0, block_data, 0, first_line_data.length);
        running_length += first_line_data.length;
        System.arraycopy(logk_data, 0, block_data, running_length, logk_data.length);
        running_length += logk_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        running_length += crlf_data.length;
        System.arraycopy(current_data, 0, block_data, running_length, current_data.length);
        running_length += current_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        return block_data;
    }
    
    /**
     * <p>Encodes image data into a byte array for sending over a network connection.</p>
     * <p>Data is encoded according to the following format:</p>
     * <code><p>"xlen: %d\r\n"</p>
     * <p>"ylen: %d\r\n"</p>
     * <p>[Binary data containing xs] + "\r\n"</p>
     * <p>[Binary data containing ys] + "\r\n"</p>
     * <p>[Binary data containing signals] + "\r\n"</p></code>
     * <p>Doubles are converted to bytes using {@link #ENDIANNESS} endianness</p>
     * <p>The image signal data is mapped to one dimension as a series of scans in the y-direction i.e.:</p>
     * <code><p>for(x = 0 -> xlen)</p>
     * <p>  for(y = 0 -> ylen)</p>
     * <p>      Append signal[x][y] to byte array</p>
     * <p>  end for</p>
     * <p>end for</p></code>
     * <p></p>
     * @param xs a double array comprising the x coordinates of the pixels in the image
     * @param ys a double array comprising the y coordinates of the pixels in the image
     * @param signals a double array containing the signal data of the image. 
     * Indexed as signals[x][y]
     * @return the image data as a byte array
     */
    private static byte[] encodeImage(double[] xs, double[] ys, double[][] signals){
        /*
        "xlen: %d\r\n", xlen
        "ylen: %d\r\n", ylen
        [Binary data containing xs] + "\r\n"
        [Binary data containing ys] + "\r\n"
        [Binary data containing signals] + "\r\n"
        */
        int xlen = xs.length;
        int ylen = ys.length;
        String size_lines = String.format("xlen: %d\r\nylen: %d\r\n", xlen, ylen);
        String crlf = "\r\n";
        
        byte[] size_line_data = size_lines.getBytes(CHARSET);
        byte[] crlf_data = crlf.getBytes(CHARSET);
        byte[] x_data = new byte[xlen*8];
        byte[] y_data = new byte[ylen*8];
        byte[] img_data = new byte[xlen*ylen*8];
        
        ByteBuffer x_bb = ByteBuffer.wrap(x_data).order(ENDIANNESS);
        ByteBuffer y_bb = ByteBuffer.wrap(y_data).order(ENDIANNESS);
        ByteBuffer img_bb = ByteBuffer.wrap(img_data).order(ENDIANNESS);
        
        for(int i = 0; i < xs.length; i++){
            x_bb.putDouble(i*8, xs[i]);
        }
        for(int i = 0; i < ys.length; i++){
            y_bb.putDouble(i*8, ys[i]);
        }
        for(int x = 0; x < xlen; x++){
            int xcontrib = x*ylen;
            for(int y = 0; y < ylen; y++){
                int indx = xcontrib + y;
                img_bb.putDouble(indx*8, signals[x][y]);
            }
        }
        
        //Append the data together
        int block_length = size_line_data.length + x_data.length + y_data.length + img_data.length + 3*crlf_data.length;
        byte[] block_data = new byte[block_length];
        int running_length = 0;
        System.arraycopy(size_line_data, 0, block_data, 0, size_line_data.length);
        running_length += size_line_data.length;
        System.arraycopy(x_data, 0, block_data, running_length, x_data.length);
        running_length += x_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        running_length += crlf_data.length;
        System.arraycopy(y_data, 0, block_data, running_length, y_data.length);
        running_length += y_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        running_length += crlf_data.length;
        System.arraycopy(img_data, 0, block_data, running_length, img_data.length);
        running_length += img_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        return block_data;
    }
    
    /**
     * Overwrites {@link #FILE_PATH_DATA} to only contain on single "%".
     * @throws FileNotFoundException 
     */
    private static void eraseDataFile() throws FileNotFoundException{
        File f = new File(FILE_PATH_DATA);
        PrintWriter pw = new PrintWriter(f);
        pw.print("%");
        pw.close();
    }
    
    /**
     * 
     * @param array
     * @param key
     * @return 
     */
    private static int findEqual(double[] array, double key){
        return findEqual(array, key, 0, array.length-1);
    }
    
    /**
     * 
     * @param array
     * @param key
     * @param min
     * @param max
     * @return 
     */
    private static int findEqual(double[] array, double key, int min, int max){
        boolean use_relative = false;
        if(tolerantEquals(key, array[min], use_relative)){
            return min;
        }
        else if(tolerantEquals(key, array[max], use_relative)){
            return max;
        }
        else if(array[min] > key || array[max] < key){
            return -1;
        }
        else{
            int mid = (max - min) / 2 + min;
            if(tolerantEquals(key, array[mid], use_relative)){
                return mid;
            }
            else if(array[mid] < key){
                return findEqual(array, key, mid, max);
            }
            else{
                return findEqual(array, key, min, mid);
            }
        }
    }
    
    /**
     * Binary searches through an descending order array to find the largest index such that array[index] &gt; value.
     * Will return -1 if all elements of array are &lt; value
     * @param array array of values sorted in descending order.
     * @param value the value that is being searched-for.
     * @return 
     */
    private static int findGreater(double[] array, double value){
        if(array[0] < value){
            return -1;
        }
        if(array[array.length - 1] > value){
            return array.length - 1;
        }
        return findLower(array, value, 0, array.length - 1);
    }
    
    /**
     * USE {@link #findGreater(double[], double) } instead.
     * @param array
     * @param value
     * @param start
     * @param stop
     * @return 
     */
    private static int findGreater(double[] array, double value, int start, int stop){
        
        if(stop - start == 1){
            return start;
        }
        else if(stop - start == 2){
            if(array[start + 1] > value){
                return start + 1;
            }
            else{
                return start;
            }
        }
        else{
            int mid = (stop - start)/2 + start;
            if(array[mid] > value){
                return findLower(array, value, mid, stop); 
            }
            else{
                return findLower(array, value, start, mid);
            }
        }
    }
    
    /**
     * Binary searches through an ascending order array to find the largest index such that array[index] &lt; value.
     * Will return -1 if all elements of array are &gt; value
     * @param array array of values sorted in ascending order.
     * @param value the value that is being searched-for.
     * @return 
     */
    private static int findLower(double[] array, double value){
        if(array[0] > value){
            return -1;
        }
        if(array[array.length - 1] < value){
            return array.length - 1;
        }
        return findLower(array, value, 0, array.length - 1);
    }
    
    /**
     * USE {@link #findLower(double[], double) } instead.
     * @param array
     * @param value
     * @param start
     * @param stop
     * @return 
     */
    private static int findLower(double[] array, double value, int start, int stop){
        
        if(stop - start == 1){
            return start;
        }
        else if(stop - start == 2){
            if(array[start + 1] < value){
                return start + 1;
            }
            else{
                return start;
            }
        }
        else{
            int mid = (stop - start)/2 + start;
            if(array[mid] < value){
                return findLower(array, value, mid, stop); 
            }
            else{
                return findLower(array, value, start, mid);
            }
        }
    }
    
    /**
     * Generates a timestamp loosely following ISO 8601
     * @return 
     */
    private static String getDateStamp(){
        Calendar cl = Calendar.getInstance();
        int year = cl.get(Calendar.YEAR);
        int month = cl.get(Calendar.MONTH) + 1;
        int day = cl.get(Calendar.DAY_OF_MONTH);
        int hour = cl.get(Calendar.HOUR_OF_DAY);
        int minute = cl.get(Calendar.MINUTE);
        int second = cl.get(Calendar.SECOND);
        String date_time = String.format("%04d-%02d-%02dT%02d:%02d:%02d", year, month, day, hour, minute, second);
        return date_time;
    }
    
    /**
     * Sends a HEAD request for <code>content_id</code> to the server and returns the ETag for the version of this content on file in the server.
     * @param sender the OutputStream for sending information to the server
     * @param receiver the InputStream for receiving information from the server
     * @param content_id the identity of the requested content. 
     * There are three pieces of content that can be sent back and forth between this program and the server:
     * <ul>
     * <li>k-curve</li>
     * <li>k-image</li>
     * <li>secm-image</li>
     * </ul>
     * @return returns the ETag for <code>content_id</code> if the content exists on the server, null otherwise.
     * @throws IOException occur when unexpected responses are received or the server sends a ststus that is not either <code>200 OK</code> or <code>404 Not found</code> 
     */
    private static String getETag(OutputStream sender, InputStream receiver, String content_id) throws IOException{
        String CRLF = "\r\n";
        String requestline = "HEAD " + content_id + " HTTP/1.1" + CRLF;
        String fields = "Date: " + getDateStamp() + CRLF;
        //send head request
        String request_full = requestline + fields + CRLF;
        sender.write(request_full.getBytes(CHARSET));
        sender.flush(); // make sure everything gets sent
        
        //listen for response
        String response_status_line = new String(readLine(receiver), CHARSET);
        
        String[] status_line_tokens = response_status_line.split("\\s+");
        //If an incorrect status message is recieved, or an unexpected status is received, throw an error
        if(!status_line_tokens[0].equals("HTTP/1.1")){
            throw new IOException("Status line did not start with HTTP/1.1");
        }
        
        //read the rest of the message to get the ETag or clear the receiver.
        String etag = null;
        int content_length = -1;
        boolean continueparsing = true;
        while(continueparsing){
            byte[] line_data = readLine(receiver);
            String line = new String(line_data, CHARSET);
            if(line.startsWith("Content-Length:")){
                String content_length_str = line.substring(15).trim();
                content_length = Integer.parseInt(content_length_str);
            }
            else if(line.startsWith("ETag: ")){
                    if(etag == null){
                        etag = line.substring(6).trim();
                    }
                    else{
                        throw new IOException("Encountered more than one ETag field.");
                    }
                }
            continueparsing = !line.equals("\r\n");
        }
        String content = "";
        if(content_length > 0){
            byte[] content_data = readBlock(receiver, content_length);
            content = new String(content_data, CHARSET);
        }
        
        if(!status_line_tokens[1].equals("200") && !status_line_tokens[1].equals("404")){
            throw new IOException("Received unexpected status code. Expected: (200|404); Received: " + status_line_tokens[1] + " " + content);
        }
        
        //process the result
        return etag;
    }
    
    /**
     * Converts the y-data of a curve y = f(x) to a byte array and hashes it according to {@link #HASH_ALGORITHM}.
     * This is used for generating ETags to reduce the amount of times data is sent over the network.
     * The doubles in the curve data are converted to bytes with {@link #ENDIANNESS} endianness.
     * @param curve the curve data to be hashed.
     * @return the hash of the given curve after it has been converted to a byte array.
     */
    private static byte[] hashCurve(double[] curve){
        //convert curve to byte array
        int len = 8*curve.length;
        byte[] bytearray = new byte[len];
        ByteBuffer bb = ByteBuffer.wrap(bytearray).order(ENDIANNESS);
        for(int i = 0; i < curve.length; i++){
            bb.putDouble(i*8, curve[i]);
        }
        //hash byte array
        MessageDigest sha256;
        try {
            sha256 = MessageDigest.getInstance(HASH_ALGORITHM);
            byte[] hash = sha256.digest(bytearray);
            return hash;
        } catch (NoSuchAlgorithmException ex) {
            
        }
        
        return new byte[0];
    }
    
    /**
     * Converts image data to a byte array and hashes it according to {@link #HASH_ALGORITHM}.
     * This is used for generating ETags to reduce the amount of times data is sent over the network.
     * The doubles in the image data are converted to bytes with {@link #ENDIANNESS} endianness.
     * The image data is mapped to one dimension as a series of scans in the y-direction i.e.:
     * <code><p>for(x = 0 -> xlen)</p>
     * <p>  for(y = 0 -> ylen)</p>
     * <p>      Append signal[x][y] to byte array</p>
     * <p>  end for</p>
     * <p>end for</p></code>
     * @param image the image data to be hashed
     * @return the hash of the given image after it has been mapped to one dimension and converted to a byte array.
     */
    private static byte[] hashImage(double[][] image){
        //convert image to byte array
        int xlen = image.length;
        int ylen = image[0].length;
        int total_len = xlen*ylen*8;
        byte[] bytearray = new byte[total_len];
        ByteBuffer bb = ByteBuffer.wrap(bytearray).order(ENDIANNESS);
        for(int x = 0; x < xlen; x++){
            int xcontrib = x*ylen;
            for(int y = 0; y < ylen; y++){
                int indx = xcontrib + y;
                bb.putDouble(indx*8, image[x][y]);
            }
        }
        //hash byte array
        MessageDigest sha256;
        try {
            sha256 = MessageDigest.getInstance(HASH_ALGORITHM);
            byte[] hash = sha256.digest(bytearray);
            return hash;
        } catch (NoSuchAlgorithmException ex) {
            
        }
        
        return new byte[0];
    }
    
    /**
     * Converts the byte arrays from {@link #hashCurve(double[])} or {@link #hashImage(double[][])} to a string containing the hexadecimal representation of the hash.
     * @param hash the hash to be converted to a hexadecimal string
     * @return the String representation of the hash
     */
    private static String hashToString(byte[] hash){
        String hash_string = "";
        for(int i = 0; i < hash.length; i++){
            hash_string = hash_string + String.format("%02x", hash[i]);
        }
        return hash_string;
    }
    
    /**
     * Uses {@link #currentToLogKappa(double)} to convert {@link #img_true} into an initial estimate for {@link #img_kappas}.
     */
    private static void initializeKappaImage(){
        int xlen = img_true.length;
        int ylen = img_true[0].length;
        img_kappas = new double[xlen][ylen];
        for(int x = 0; x < xlen; x++){
            for(int y = 0; y < ylen; y++){
                if(x == 0 && y == 60){
                    System.out.println("break");
                }
                img_kappas[x][y] = currentToLogKappa(img_true[x][y]);
            }
        }
    }
    
    /**
     * Converts a logk for a spot at the surface to a scaled current that would 
     * be observed by a microelectrode above the surface.This function is inverted
     * by {@link #currentToLogKappa(double)}.
     * @param logk The log rate constant
     * @return 
     */
    private static double logKappaToCurrent(double log_kappa){
        int len_m1 = ki_logks.length - 1;
        if(log_kappa > ki_logks[0] && log_kappa < ki_logks[len_m1]){
            int lower = findLower(ki_logks, log_kappa);
            double kappa_lower = ki_logks[lower];
            double kappa_upper = ki_logks[lower + 1];
            double current_lower = ki_currents[lower];
            double current_upper = ki_currents[lower + 1];
            
            double kappa_distance = kappa_upper - kappa_lower;
            double fact_lower = (kappa_upper - log_kappa)/kappa_distance;
            double fact_upper = 1.0-fact_lower;
            return current_lower*fact_lower + current_upper*fact_upper;
        }
        else if(log_kappa <= ki_logks[0]){
            return ki_currents[0];
        }
        else{
            return ki_currents[len_m1];
        }
    }
    
    /**
     * Sends a post-processing request to the server, sending along an SECM Image and awaiting a new k image to simulate.
     * The server should either send 
     * <ul>
     * <li>A "200 OK" response with a new k image. In which case this function decodes the k image and writes new values to {@link #img_x_coordinates}, {@link #img_y_coordinates} and {@link #img_kappas}.</li>
     * <li>A "204 No Content" response indicating convergence. In which case this function sets {@link #img_x_coordinates}, {@link #img_y_coordinates} and {@link #img_kappas} to null.</li>
     * <li>Any other code indicating an error has occurred. In which case an IOException is thrown</li>
     * </ul>
     * 
     * @param sender the OutputStream to the server.
     * @param receiver the InputStream from the server.
     * @param xs the x-coordinates for the current image.
     * @param ys the y-coordinates for the current image.
     * @param currentimg the current image. Indexed as <code>currentimg[x][y]</code>.
     * @throws IOException Thrown when networking errors occur or an unexpected response is received from the server.
     */
    private static void postSecmImage(OutputStream sender, InputStream receiver, double[] xs, double[] ys, double[][] currentimg) throws IOException{
        //POST SECM Image
        String etag = hashToString(hashImage(currentimg));
        byte[] image_data = encodeImage(xs, ys, currentimg);
        int content_length = image_data.length;
        String post_header = "POST secm-image HTTP/1.1\r\n"
                + "Date: " + getDateStamp() + "\r\n"
                + "ETag: " + etag + "\r\n"
                + "Content-Encoding: " + VERSION + "\r\n"
                + "Content-Length: " + content_length + "\r\n"
                + "Content-Type: IMAGE\r\n"
                + "\r\n";
        sender.write(post_header.getBytes(CHARSET));
        sender.write(image_data);
        sender.flush();
        
        //listen for response
        String response_status_line = new String(readLine(receiver), CHARSET);
        
        String[] status_line_tokens = response_status_line.split("\\s+");
        //If an incorrect status message is recieved, or an unexpected status is received, throw an error
        if(!status_line_tokens[0].equals("HTTP/1.1")){
            throw new IOException("Status line did not start with HTTP/1.1");
        }
        
        if(!status_line_tokens[1].equals("200")){
            throw new IOException("Received unexpected status code. Expected: 200; Received: " + status_line_tokens[1]);
        }
        
        //read the rest of the headers to get the content length.
        boolean continueparsing = true;
        String response_field_line;
        content_length = -1;
        while(continueparsing){
            response_field_line = new String(readLine(receiver), CHARSET);
            if(response_field_line.startsWith("Content-Length:")){
                String content_length_str = response_field_line.substring(15).trim();
                content_length = Integer.parseInt(content_length_str);
            }
            continueparsing = !response_field_line.equals("\r\n");
        }
        
        if(content_length <= 0){
            throw new IOException("Response to POST request did not contain content.");
        }
        
        byte[] data_block = readBlock(receiver, content_length);
        
        decodeIncomingKImage(data_block);
    }
    
    /**
     * Reads the response to PUT requests from the server, ensuring that the data was received correctly. 
     * This serves to clear the server response from the InputStream and take no further action if everything operates correctly.
     * If an incorrect response is received, an IOException will be thrown to halt this program.
     * @param receiver The InputStream from the server.
     * @throws IOException To be thrown if there are any errors that occur on the server side or in the case of an incorrect response from the server.
     */
    private static void processPutResponse(InputStream receiver) throws IOException{
        //listen for response
        byte[] line_data = readLine(receiver);
        String response_status_line = new String(line_data, CHARSET);
        
        String[] status_line_tokens = response_status_line.split("\\s+");
        //If an incorrect status message is recieved, or an unexpected status is received, throw an error
        if(!status_line_tokens[0].equals("HTTP/1.1")){
            throw new IOException("Status line did not start with HTTP/1.1");
        }
        
        int content_length = -1;
        boolean continueparsing = true;
        while(continueparsing){
            line_data = readLine(receiver);
            String line = new String(line_data, CHARSET);
            if(line.startsWith("Content-Length:")){
                String content_length_str = line.substring(15).trim();
                content_length = Integer.parseInt(content_length_str);
            }
            continueparsing = !line.equals("\r\n");
        }
        String content = "";
        if(content_length > 0){
            byte[] content_data = readBlock(receiver, content_length);
            content = new String(content_data, CHARSET);
        }
        
        if(!status_line_tokens[1].equals("200")){
            throw new IOException("Received unexpected status code to PUT request. Expected: 200; Received: " + status_line_tokens[1] + " " + content.trim());
        }
    }
    
    /**
     * Handles the process of sending a PUT request for the k-curve to the server.
     * This starts by calling {@link #getETag(java.io.OutputStream, java.io.InputStream, java.lang.String)} to check the copy of the k-curve on the server by making a HEAD request and comparing the ETag to the hash of the k-curve.
     * If the ETag and hash match, the server is up-to-date and the data is not sent over.
     * If the ETag does not match or a 404 Not Found response is received, a PUT request is made, sending the k-curve data on to the server.
     * {@link #processPutResponse(java.io.InputStream)} is used to ensure the server received the data correctly.
     * @param sender The OutputStream to the server.
     * @param receiver The InputStream from the server.
     * @param logks The logk data. Must have the same size as <code>currents</code>
     * @param currents The current data. Must have the same size as <code>logks</code>
     * @throws IOException Will be thrown if there are any errors when contacting the server or if an unexpected response is received.
     * @see #getETag(java.io.OutputStream, java.io.InputStream, java.lang.String) 
     */
    private static void putKCurve(OutputStream sender, InputStream receiver, double[] logks, double[] currents) throws IOException{
        /*
        HEAD kcurve
            if 200 OK received compare recieved hash to curve's hash
            if 204 No Content received OR the hashes do not match, send kurve data over
        */
        //HEAD kcurve
        String etag_new = hashToString(hashCurve(currents));
        String etag_cached = getETag(sender, receiver, "k-curve");
        //if 200 OK received compare recieved hash to curve's hash
        //if 404 Not Found received OR the hashes do not match, send kurve data over
        boolean send_curve = true;
        if(etag_cached != null){
            send_curve = !etag_cached.equals(etag_new);
        }
        if(send_curve){
            byte[] curve_data = encodeCurve(logks, currents);
            int content_length = curve_data.length;
            String put_header = "PUT k-curve HTTP/1.1\r\n" 
                    + "Date: " + getDateStamp() + "\r\n"
                    + "ETag: " + etag_new + "\r\n"
                    + "Content-Encoding: " + VERSION + "\r\n"
                    + "Content-Length: " + content_length + "\r\n"
                    + "Content-Type: IMAGE\r\n"
                    + "\r\n";
            sender.write(put_header.getBytes(CHARSET));
            sender.write(curve_data);
            sender.flush();
            
            processPutResponse(receiver);
        }
    }
    
    /**
     * Handles the process of sending a PUT request for the k-image to the server.
     * This starts by calling {@link #getETag(java.io.OutputStream, java.io.InputStream, java.lang.String)} to check the copy of the k-image on the server by making a HEAD request and comparing the ETag to the hash of the k-image.
     * If the ETag and hash match, the server is up-to-date and the data is not sent over.
     * If the ETag does not match or a 404 Not Found response is received, a PUT request is made, sending the k-image data on to the server.
     * {@link #processPutResponse(java.io.InputStream)} is used to ensure the server received the data correctly.
     * @param sender The OutputStream to the server.
     * @param receiver The InputStream from the server.
     * @param xs The x position data. Indexed as <code>xs[x]</code>.
     * @param ys The y position data. Indexed as <code>ys[y]</code>.
     * @param logkimg The k-image data. Indexed as <code>logkimg[x][y]</code>.
     * @throws IOException Will be thrown if there are any errors when contacting the server or if an unexpected response is received.
     */
    private static void putKImage(OutputStream sender, InputStream receiver, double[] xs, double[] ys, double[][] logkimg) throws IOException{
        /*
        HEAD image
            if 200 OK received compare recieved hash to image's hash
            if 204 No Content received OR the hashes do not match, send kurve data over
        */
        //HEAD image
        String etag_new = hashToString(hashImage(logkimg));
        String etag_cached = getETag(sender, receiver, "k-image");
        //if 200 OK received compare recieved hash to curve's hash
        //if 404 Not Found received OR the hashes do not match, send kurve data over
        boolean send_image = true;
        if(etag_cached != null){
            send_image = !etag_cached.equals(etag_new);
        }
        if(send_image){
            byte[] image_data = encodeImage(xs, ys, logkimg);
            int content_length = image_data.length;
            String put_header = "PUT k-image HTTP/1.1\r\n" 
                    + "Date: " + getDateStamp() + "\r\n"
                    + "ETag: " + etag_new + "\r\n"
                    + "Content-Encoding: " + VERSION + "\r\n"
                    + "Content-Length: " + content_length + "\r\n"
                    + "Content-Type: IMAGE\r\n"
                    + "\r\n";
            sender.write(put_header.getBytes(CHARSET));
            sender.write(image_data);
            sender.flush();
            
            processPutResponse(receiver);
        }
    }
    
    /**
     * Handles the process of sending a PUT request for the k-image to the server.
     * This starts by calling {@link #getETag(java.io.OutputStream, java.io.InputStream, java.lang.String)} to check the copy of the k-image on the server by making a HEAD request and comparing the ETag to the hash of the k-image.
     * If the ETag and hash match, the server is up-to-date and the data is not sent over.
     * If the ETag does not match or a 404 Not Found response is received, a PUT request is made, sending the k-image data on to the server.
     * {@link #processPutResponse(java.io.InputStream)} is used to ensure the server received the data correctly.
     * @param sender The OutputStream to the server.
     * @param receiver The InputStream from the server.
     * @param xs The x position data. Indexed as <code>xs[x]</code>.
     * @param ys The y position data. Indexed as <code>ys[y]</code>.
     * @param trueimg The true secm image data. Indexed as <code>trueimg[x][y]</code>.
     * @throws IOException Will be thrown if there are any errors when contacting the server or if an unexpected response is received.
     */
    private static void putTrueSecmImage(OutputStream sender, InputStream receiver, double[] xs, double[] ys, double[][] trueimg) throws IOException{
        /*
        HEAD image
            if 200 OK received compare recieved hash to image's hash
            if 404 Not Found received OR the hashes do not match, send target image data over
        */
        //HEAD image
        String etag_new = hashToString(hashImage(trueimg));
        String etag_cached = getETag(sender, receiver, "target-image");
        //if 200 OK received compare recieved hash to curve's hash
        //if 404 Not Found received OR the hashes do not match, send target image data over
        boolean send_image = true;
        if(etag_cached != null){
            send_image = !etag_cached.equals(etag_new);
        }
        if(send_image){
            byte[] image_data = encodeImage(xs, ys, trueimg);
            int content_length = image_data.length;
            String put_header = "PUT target-image HTTP/1.1\r\n" 
                    + "Date: " + getDateStamp() + "\r\n"
                    + "ETag: " + etag_new + "\r\n"
                    + "Content-Encoding: " + VERSION + "\r\n"
                    + "Content-Length: " + content_length + "\r\n"
                    + "Content-Type: IMAGE\r\n"
                    + "\r\n";
            sender.write(put_header.getBytes(CHARSET));
            sender.write(image_data);
            sender.flush();
            
            processPutResponse(receiver);
        }
    }
    
    /**
     * Reads <code>length</code> bytes from the InputStream
     * @param input_stream
     * @param length
     * @return
     * @throws IOException 
     */
    private static byte[] readBlock(InputStream input_stream, int length) throws IOException{
        byte[] block = new byte[length];
        int index;
        for(index = 0; index < length; index ++){
            int currentbyte = input_stream.read();
            if(currentbyte >= 0){
                block[index] = (byte)(currentbyte & 0xFF);
            }
            else{
                throw new IOException("Encountered end of message unexpectedly.");
            }
        }
        return block;
    }
    
    /**
     * Reads from the rightmost column of {@link #FILE_PATH_DATA} and returns the result as an array of doubles
     * @return 
     * @throws FileNotFoundException 
     */
    private static double[] readData() throws FileNotFoundException{
        File f = new File(FILE_PATH_DATA);
        Scanner s = new Scanner(f);
        int count = 0;
        while(s.hasNextLine()){
            String ln = s.nextLine();
            if(!ln.startsWith("%")){
                count ++;
            }
        }
        s.close();
        double[] data = new double[count];
        s = new Scanner(f);
        count = 0;
        while(s.hasNextLine()){
            String ln = s.nextLine();
            if(!ln.startsWith("%")){
                String[] linedata = ln.trim().split("\\s+");// split whilespace separated columns
                data[count] = Double.parseDouble(linedata[linedata.length -1]);//read from the rightmost column
                count ++;
            }
        }
        s.close();
        return data;
    }
    
    /**
     * Reads through the control file, pulling out information for the reactivity grid, the sampled points and the experimentally observed secm currents.
     * This method instantiates:
     * <ul>
     * <li>{@link #grid}</li>
     * <li>{@link #sample_xs}</li>
     * <li>{@link #sample_ys}</li>
     * <li>{@link #physical_xs}</li>
     * <li>{@link #physical_ys}</li>
     * <li>{@link #min_x}</li>
     * <li>{@link #min_y}</li>
     * </ul>
     * @param filepath The path to the control file.
     * @throws FileNotFoundException 
     */
    private static void readInstructionFile(String filepath) throws IOException{
        File f = new File(filepath);
        double[] samplexs;
        double[] sampleys;
        String sep = ",";
        
        Scanner s = new Scanner(f);
        if(s.hasNextLine()){
            String fl = s.nextLine();
            if(fl.equalsIgnoreCase("##ENCODING: csv")){
                sep = ",";
            }
            else if(fl.equalsIgnoreCase("##ENCODING: tsv")){
                sep = "\t";
            }
            else{
                throw new IOException("Unexpected file encoding.");
            }
        }
        else{
            throw new IOException("File contains no readable lines.");
        }

        //X header
        int xstart = 0;
        int xstep = 0;
        int xnum = 0;
        if(s.hasNextLine()){
            String fl = s.nextLine();
        }
        else{
            throw new IOException("File ended before x-header.");
        }
        if(s.hasNextLine()){
            String fl = s.nextLine();
            String[] tokens = fl.substring(1).trim().split(",");
            xstart = Integer.parseInt(tokens[0]);
            xstep = Integer.parseInt(tokens[1]);
            xnum = Integer.parseInt(tokens[2]);
        }
        else{
            throw new IOException("Error parsing x-header.");
        }

        //Y header
        int ystart = 0;
        int ystep = 0;
        int ynum = 0;
        if(s.hasNextLine()){
            String fl = s.nextLine();
        }
        else{
            throw new IOException("File ended before y-header.");
        }
        if(s.hasNextLine()){
            String fl = s.nextLine();
            String[] tokens = fl.substring(1).trim().split(",");
            ystart = Integer.parseInt(tokens[0]);
            ystep = Integer.parseInt(tokens[1]);
            ynum = Integer.parseInt(tokens[2]);
        }
        else{
            throw new IOException("Error parsing y-header.");
        }

        int asize = (xnum)*(ynum);
        int present_index = 0;

//        trueimage = new double[asize];
//        physicalxs = new double[asize];
//        physicalys = new double[asize];
        samplexs = new double[xnum];
        sampleys = new double[ynum];
        
        LinkedList<Double> x_coordinate_list = new LinkedList<Double>();
        LinkedList<Double> y_coordinate_list = new LinkedList<Double>();

        while(s.hasNextLine()){
            String line = s.nextLine();
            if(!line.startsWith("#")){
                String[] linesplit = line.split(sep);
                int x = Integer.parseInt(linesplit[0]);
                int y = Integer.parseInt(linesplit[1]);
                double px = Double.parseDouble(linesplit[3]);
                double py = Double.parseDouble(linesplit[4]);
                
                addInOrder(x_coordinate_list, px);
                addInOrder(y_coordinate_list, py);

                //check if x,y is one of the points to be sampled
                boolean xvalid = (x >= xstart) && (x < xstart + xnum*xstep) && ((x-xstart)%xstep == 0);
                boolean yvalid = (y >= ystart) && (y < ystart + ynum*ystep) && ((y-ystart)%ystep == 0);
                if(xvalid && yvalid && present_index < asize){
                    int x_index = (x-xstart)/xstep;
                    int y_index = (y-ystart)/ystep;
                    samplexs[x_index] = px;
                    sampleys[y_index] = py;
                    present_index ++;
                }

            }
        }
        s.close();
        
        img_x_coordinates = new double[x_coordinate_list.size()];
        img_y_coordinates = new double[y_coordinate_list.size()];
        img_true = new double[x_coordinate_list.size()][y_coordinate_list.size()];
        
        ListIterator<Double> x_coordinate_li = x_coordinate_list.listIterator();
        ListIterator<Double> y_coordinate_li = y_coordinate_list.listIterator();
        
        int index = 0;
        while(x_coordinate_li.hasNext()){
            img_x_coordinates[index] = x_coordinate_li.next();
            index ++;
        }
        index = 0;
        while(y_coordinate_li.hasNext()){
            img_y_coordinates[index] = y_coordinate_li.next();
            index ++;
        }
        s = new Scanner(f);
        while(s.hasNextLine()){
            String line = s.nextLine();
            if(!line.startsWith("#")){
                String[] linesplit = line.split(sep);
                double px = Double.parseDouble(linesplit[3]);
                double py = Double.parseDouble(linesplit[4]);
                double current = Double.parseDouble(linesplit[5]);
                
                int x = findEqual(img_x_coordinates, px);
                int y = findEqual(img_y_coordinates, py);
                img_true[x][y] = current;

            }
        }
        s.close();
        
        if(present_index != asize){
            throw new FileNotFoundException("Expected " + asize + " points. Found: " + present_index + ".");
        }
        
        sim_x_coordinates = samplexs;
        sim_y_coordinates = sampleys;        
    }
    
    /**
     * Reads one line of http traffic, returning all bytes in the line including the trailing \r\n
     * @param input_stream
     * @return
     * @throws IOException 
     */
    private static byte[] readLine(InputStream input_stream) throws IOException{
        int currentbyte = -1;
        String crlf = "\r\n";
        byte[] crlf_data = crlf.getBytes(CHARSET);
        byte[] crlf_detection_buffer = new byte[crlf_data.length];
        boolean continue_reading = true;
        LinkedList<Integer> line_data = new LinkedList<Integer>();
        int size = 0;
        while(continue_reading){
            currentbyte = input_stream.read();
            if(currentbyte < 0){//if at end of stream, break out of the loop.
                continue_reading = false;
                throw new IOException("InputStream reached its end.");
                //break;//uncomment if throw is removed
            }
            System.out.print((char)currentbyte);
            for(int cdb = 0; cdb < crlf_detection_buffer.length - 1; cdb ++){
                crlf_detection_buffer[cdb] = crlf_detection_buffer[cdb + 1];
            }
            crlf_detection_buffer[crlf_detection_buffer.length - 1] = (byte)(currentbyte & 0xFF);
            //add data to the line
            line_data.add(currentbyte);
            //check line end condition
            continue_reading = false;
            for(int cdb = 0; cdb < crlf_data.length; cdb++){
                if(crlf_detection_buffer[cdb] != crlf_data[cdb]){
                    continue_reading = true;
                    break;
                }
            }
            size ++;
            if(size > MAX_NON_BODY_LENGTH){
                throw new IOException("Read maximum number of bytes before hitting end of line.");
            }
        }
        //collect the line data into one array
        byte[] line_bytes = new byte[line_data.size()];
        ListIterator<Integer> line_data_iterator = line_data.listIterator();
        int index = 0;
        while(line_data_iterator.hasNext()){
            int data = line_data_iterator.next();
            line_bytes[index] = (byte)(data & 0xFF);
            index ++;
        }
        return line_bytes;
    }
    
    /**
     * Handles the simulation of SECM images
     * @param a the ME radius
     * @param D the diffusion coefficient
     * @param L the dimensionless tip to substrate distance
     * @throws IOException 
     */
    private static void simulateImage(double a, double Rg, double D, double L) throws IOException{
        writeReactivityFile(img_x_coordinates, img_y_coordinates, img_kappas);
        Model model = run(a, Rg, D, L, sim_x_coordinates, sim_y_coordinates);
        double[] result = readData();
        int i = 0;
        img_sim = new double[sim_x_coordinates.length][sim_y_coordinates.length];
        for(int x = 0; x < sim_x_coordinates.length; x++){
            for(int y = 0; y < sim_y_coordinates.length; y++){
                img_sim[x][y] = result[i];
                i++;
            }
        }
        eraseDataFile();
        
    }
    
    /**
     * Handles the simulation and data processing that will be used by {@link #logKappaToCurrent(double)} to convert rate constants to currents.
     * @param L The normalized tip to substrate distance.
     */
    private static void simulateKCurve(double a, double Rg, double D, double L, boolean verbose) throws IOException{
        // generate a reactivity file where a 40.0a by 40.0a square has a reactivity of 1
        double[] xspace = new double[]{0, 200, 400};
        double[] yspace = new double[]{0, 200, 400};
        double[][] grid_data = new double[][]{{1, 1, 1},
            {1, 1, 1},
            {1, 1, 1}};
        
        double amplitude = LOG_KAPPA_HIGH - LOG_KAPPA_LOW;
        int k_datapoints = 9;
        double[] logk_data = new double[k_datapoints];
        double[] k_data = new double[k_datapoints];
        for(int i = 0; i < k_datapoints; i++){
            double mult = ((double)i)/((double)k_datapoints);
            logk_data[i] = mult*amplitude + LOG_KAPPA_LOW;
            k_data[i] = Math.pow(10, logk_data[i]);
        }
        
        writeReactivityFile(xspace, yspace, grid_data);
        Model model = runk(a, Rg, D, L, xspace[1], yspace[1], k_data);
        
        ki_currents = readData();
        eraseDataFile();
        ki_logks = new double[k_datapoints];
        System.arraycopy(logk_data, 0, ki_logks, 0, k_datapoints);
        
        if(verbose){
            writeKCurve(logk_data, ki_currents);
        }
    }
    
    /**
     * Checks if d1 and d2 are within a certain cutoff (1E-9) of one another
     * @param d1
     * @param d2
     * @param use_relative
     * @return 
     */
    private static boolean tolerantEquals(double d1, double d2, boolean use_relative){
        double diff = Math.abs(d2-d1);
        final double TOLERANCE = 1E-9;
        if(use_relative){
            double avg = 0.5*Math.abs(d1) + 0.5*Math.abs(d2);
            if(avg >= TOLERANCE){
                return (diff / avg) < TOLERANCE;
            }
            else{
                return diff < TOLERANCE;
            }
        }
        else{
            return diff < TOLERANCE;
        }
        
    }
    
    /**
     * Writes k-curve data to {@link #FILE_PATH_KLOG} in a comma separated values (csv) format.
     * @param k_data The logk data. Must have the same size as <code>currents</code>
     * @param currents The current data. Must have the same size as <code>k_data</code>
     * @throws IOException If the {@link #FILE_PATH_KLOG} cannot be created or written to.
     */
    private static void writeKCurve(double[] k_data, double[] currents) throws IOException{
        File f = new File(FILE_PATH_KLOG);
        f.createNewFile();
        PrintWriter pw = new PrintWriter(f);
        pw.print("#log10(k/1[m/s]), i[A]");
        for(int i = 0; i < k_data.length; i++){
            pw.print(String.format("\n%f,%e", k_data[i], currents[i]));
        }
        pw.close();
    }
    
    /**
     * Writes the reactivity map to a file that is read by the COMSOL simulation.
     * {@link #FILE_PATH_REACTIVITY} controls where this data is written
     * @param xs The x position data. Indexed as <code>xs[x]</code>.
     * @param ys The y position data. Indexed as <code>ys[y]</code>.
     * @param logks The k-image data. Indexed as <code>logks[x][y]</code>.
     * @throws IOException If the {@link #FILE_PATH_KLOG} cannot be created or written to.
     */
    private static void writeReactivityFile(double[] xs, double[] ys, double[][] logks) throws IOException{
        File f = new File(FILE_PATH_REACTIVITY);
        f.createNewFile();
        PrintWriter pw = new PrintWriter(new BufferedWriter(new FileWriter(f)));
        for(int x = 0; x < xs.length; x++){
            for(int y = 0; y < ys.length; y++){
                double k = Math.pow(10, logks[x][y]);
                if(x != 0 || y != 0){
                    pw.print("\n" + xs[x] + "," + ys[y] + "," + k);
                }
                else{
                    pw.print(xs[x] + "," + ys[y] + "," + k);
                }
            }
        }
        pw.close();
    }
    
    /**
     * Holds the currents from the logk-i curve.
     */
    private static double[] ki_currents;
    
    /**
     * Holds the logk data from the logk-i curve.
     */
    private static double[] ki_logks;
    
    /**
     * Holds the image data for the k-image. 
     * Indexed as <code>img_kappas[x][y]</code>.
     * In normalized units kappa = k[m/s]*a/D
     */
    private static double[][] img_kappas;
    
    /**
     * Holds the image data for the true secm-image. Indexed as <code>img_sim[x][y]</code>.
     */
    private static double[][] img_sim;
    
    /**
     * Holds the image data for the target-image. Indexed as <code>img_true[x][y]</code>.
     */
    private static double[][] img_true;
    
    /**
     * Holds the x-data for the k-image. Indexed as <code>img_x_coordinates[x]</code>.
     */
    private static double[] img_x_coordinates;
    
    /**
     * Holds the y-data for the k-image. Indexed as <code>img_y_coordinates[y]</code>.
     */
    private static double[] img_y_coordinates;
    
    /**
     * Holds the x-data for the k-image. Indexed as <code>img_x_coordinates[x]</code>.
     */
    private static double[] sim_x_coordinates;
    
    /**
     * Holds the y-data for the k-image. Indexed as <code>img_y_coordinates[y]</code>.
     */
    private static double[] sim_y_coordinates;
    
    /**
     * The Charset to be used when sending messages to and from the server.
     */
    private static final Charset CHARSET = Charset.forName("US-ASCII");
    
    /**
     * The ByteOrder to be used when encoding and decoding double to and from byte[]
     */
    private static final ByteOrder ENDIANNESS = ByteOrder.LITTLE_ENDIAN;
    
    /**
     * The file path for COMSOL's data output file
     */
    private static final String FILE_PATH_DATA = "data.txt";
    
    /**
     * The file path to which the logk-i curve will be written
     */
    private static final String FILE_PATH_KLOG = "kcurve.csv";
    
    /**
     * The file path to which  the k-image that COMSOL will use is to be written.
     */
    private static final String FILE_PATH_REACTIVITY = "func.csv";
    
    /**
     * The hashing algorithm to be used when generating ETags.
     * @see java.security.MessageDigest#getInstance(java.lang.String) 
     */
    private static final String HASH_ALGORITHM = "SHA-256";
    
    /**
     * The host name for communicating with the deconvolution service server.
     * Set to null (the for loopback)
     */
    private static final String HOST = null;
    
    /**
     * The logk value above which no change in current is expected
     */
    private static final double LOG_KAPPA_HIGH = -2;
    
    /**
     * The logk value below which no change in current is expected
     */
    private static final double LOG_KAPPA_LOW = -6;
    
    /**
     * The maximum length of the status line or the fields in HTTP message headers
     */
    private static final int MAX_NON_BODY_LENGTH = 512;//half a kilobyte
    
    /**
     * The port to use for communicating with the deconvolution service server.
     */
    private static final int PORT = 4091;
    
    /**
     * The version of encoding that is used when communicating data to the server.
     */
    private static final String VERSION = "0.1";
}

class Model{
    
}
