package secm_img_sim_client;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Calendar;
import java.util.Scanner;

/**
 * Collection of methods for attempts to use modified Richardson-Lucy (R-L)
 * deconvolution with scanning electrochemical microscopy (SECM) images.
 * @author Nathaniel Leslie
 */
public class SecmImgSimMain {

    /**
     * Dummy method for an autogenerated run method for COMSOL responsible for simulating an SECM image
     * @param L
     * @param xpositions
     * @param ypositions 
     */
    static Model run(double L, double[] xpositions, double[] ypositions){
        return new Model();
    }
    
    /**
     * Dummy method for an autogenerated run method for COMSOL responsible for simulating a k-i curve
     * @param L
     * @param xposition
     * @param yposition 
     */
    static Model runk(double L, double xposition, double yposition, double[] ks){
        return new Model();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
    }
    
    static double[][] convolve2D(double[][] f, double[][] h){
        return new double[][]{{}};
    }
    
    /**
     * Converts a scaled current signal to the approximate logk value that may have generated it.
     * This serves as an inverse for {@link #logkToCurrent(double)}.
     * Newton's method is used to approximate this logk value.
     * @param scaled_current The scaled current as a value between 0 and 1.
     * @return the logk that will result in current when used as an argument for {@link #logkToCurrent(double)}.
     */
    static double currentToLogk(double scaled_current){
        double perturbation_logk = 0.01; //the perturbation to use when approximating the derivative for #logkToCurrent(double).
        double threshold = 0.005; //the threshold for determining convergence (differences in candidate logk that fall below this value will be considered converged).
        int iterations = 8; //number of iterations of Newton's method
        
        double candidate_logk = 0.5*(LOGK_HIGH - LOGK_LOW); //initial guess for logk (should be located in the sloped portion of the k-i curve).
        double candidate_i;
        double derivative;
        double old_candidate;
        
        do{
            old_candidate = candidate_logk;
            candidate_i = logkToCurrent(candidate_logk);
            derivative = (logkToCurrent(candidate_logk + perturbation_logk) - candidate_i)/ perturbation_logk;
            
            candidate_logk -= (candidate_i - scaled_current)/derivative;
            
            iterations --;
        }while(iterations > 0 && Math.abs(old_candidate - candidate_logk) > threshold);
        
        return candidate_logk;
    }
    
    /**
     * Overwrites {@link #FILE_PATH_DATA}
     * @throws FileNotFoundException 
     */
    static void eraseDataFile() throws FileNotFoundException{
        File f = new File(FILE_PATH_DATA);
        PrintWriter pw = new PrintWriter(f);
        pw.print("%");
        pw.close();
    }
    
    static double[][] fastFourierTransform(double[] data){
        return new double[][]{{}};
    }
    
    /**
     * Generates a timestamp loosely following ISO 8601
     * @return 
     */
    static String getDateStamp(){
        Calendar cl = Calendar.getInstance();
        int year = cl.get(Calendar.YEAR);
        int month = cl.get(Calendar.MONTH) + 1;
        int day = cl.get(Calendar.DAY_OF_MONTH);
        int hour = cl.get(Calendar.HOUR_OF_DAY);
        int minute = cl.get(Calendar.MINUTE);
        int second = cl.get(Calendar.SECOND);
        String date_time = String.format("[%04d-%02d-%02dT%02d:%02d:%02d]", year, month, day, hour, minute, second);
        return date_time;
    }
    
    /**
     * Converts a logk for a spot at the surface to a scaled current that would 
     * be observed by a microelectrode above the surface.This function is inverted
     * by {@link #currentToLogk(double)}.
     * @param logk The log rate constant
     * @return 
     */
    static double logkToCurrent(double logk){
        return 1;
    }
    
    /**
     * Reads from the rightmost column of {@link #FILE_PATH_DATA} and returns the result as an array of doubles
     * @return 
     * @throws FileNotFoundException 
     */
    static double[] readData() throws FileNotFoundException{
        File f = new File(FILE_PATH_DATA);
        Scanner s = new Scanner(f);
        int count = 0;
        while(s.hasNextLine()){
            String ln = s.nextLine();
            if(!ln.startsWith("%")){
                count ++;
            }
        }
        s.close();
        double[] data = new double[count];
        s = new Scanner(f);
        count = 0;
        while(s.hasNextLine()){
            String ln = s.nextLine();
            if(!ln.startsWith("%")){
                String[] linedata = ln.trim().split("\\s+");// split whilespace separated columns
                data[count] = Double.parseDouble(linedata[linedata.length -1]);//read from the rightmost column
                count ++;
            }
        }
        s.close();
        return data;
    }
    
    /**
     * Handles the simulation and data processing that will be used by {@link #logkToCurrent(double)} to convert rate constants to currents.
     * @param L The normalized tip to substrate distance.
     */
    static void simulateKCurve(double L, boolean verbose) throws IOException{
        double[] xspace = new double[]{0, 200, 400};
        double[] yspace = new double[]{0, 200, 400};
        double[][] grid_data = new double[][]{{1, 1, 1},
            {1, 1, 1},
            {1, 1, 1}};
        
        double amplitude = LOGK_HIGH - LOGK_LOW;
        int k_datapoints = (int)amplitude;
        double[] logk_data = new double[k_datapoints];
        double[] k_data = new double[k_datapoints];
        for(int i = 0; i < k_datapoints; i++){
            double mult = ((double)i)/((double)k_datapoints);
            logk_data[i] = mult*amplitude + LOGK_LOW;
            k_data[i] = Math.pow(10, logk_data[i]);
        }
        
        writeReactivityFile(xspace, yspace, grid_data);
        Model model = runk(L, xspace[1], yspace[1], k_data);
        
        double[] ki_currents = readData();
        eraseDataFile();
        ki_logks = new double[k_datapoints];
        System.arraycopy(k_data, 0, ki_logks, 0, k_datapoints);
        
        if(verbose){
            writeKCurve(k_data, ki_currents);
        }
    }
    
    static void writeKCurve(double[] k_data, double[] currents) throws FileNotFoundException{
        File f = new File(FILE_PATH_KLOG);
        PrintWriter pw = new PrintWriter(f);
        pw.print("#log10(k/1[m/s]), i[A]");
        for(int i = 0; i < k_data.length; i++){
            pw.print(String.format("\n%f,%f", k_data[i], currents[i]));
        }
        pw.close();
    }
    
    static void writeReactivityFile(double[] xs, double[] ys, double[][] logks) throws IOException{
        File f = new File(FILE_PATH_REACTIVITY);
        PrintWriter pw = new PrintWriter(new BufferedWriter(new FileWriter(f)));
        for(int x = 0; x < xs.length; x++){
            for(int y = 0; y < ys.length; y++){
                double k = Math.pow(10, logks[x][y]);
                if(x != 0 || y != 0){
                    pw.print("\n" + xs[x] + "," + ys[y] + "," + k);
                }
                else{
                    pw.print(xs[x] + "," + ys[y] + "," + k);
                }
            }
        }
        pw.close();
    }
    
    static double[] ki_currents;
    
    static double[] ki_logks;
    
    static final String FILE_PATH_DATA = "data.txt";
    
    static final String FILE_PATH_KLOG = "kcurve.csv";
    
    static final String FILE_PATH_REACTIVITY = "func.csv";
    
    /**
     * The logk value above which no change in current is expected
     */
    static final double LOGK_HIGH = -2;
    
    /**
     * The logk value below which no change in current is expected
     */
    static final double LOGK_LOW = -6;
    
}

class Model{
    
}
