package secm_img_sim_client;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.Charset;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Calendar;
import java.util.Scanner;

/**
 * Collection of methods for attempts to use modified Richardson-Lucy (R-L)
 * deconvolution with scanning electrochemical microscopy (SECM) images.
 * @author Nathaniel Leslie
 */
public class SecmImgSimMain {

    /**
     * Dummy method for an autogenerated run method for COMSOL responsible for simulating an SECM image
     * @param L
     * @param xpositions
     * @param ypositions 
     */
    static Model run(double L, double[] xpositions, double[] ypositions){
        return new Model();
    }
    
    /**
     * Dummy method for an autogenerated run method for COMSOL responsible for simulating a k-i curve
     * @param L
     * @param xposition
     * @param yposition 
     */
    static Model runk(double L, double xposition, double yposition, double[] ks){
        return new Model();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args){
        // TODO code application logic here
        /*
        https://docs.oracle.com/javase/tutorial/networking/sockets/readingWriting.html
        https://docs.oracle.com/javase/tutorial/networking/sockets/clientServer.html
        https://docs.oracle.com/javase/8/docs/api/java/net/Socket.html
        */
        Socket deconv_service_socket = null;
        OutputStream sender = null;
        InputStream receiver = null;
        
        try{
            deconv_service_socket = new Socket(HOST, PORT);
            sender = deconv_service_socket.getOutputStream();
            receiver = deconv_service_socket.getInputStream();
            
            //read secm image [ ]
            
            //simulate kcurves [ ]
            
            //initialize kimage [ ]
            
            //PUT kcurve [x]
            
            //PUT kimage [x]
            
            //LOOP:
            
                //simulate SECM image [ ]

                //POST SECM image [x]
            
            //:END LOOP
            
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            if(sender != null){
                try{
                    sender.close();
                }catch(Exception e){
                    
                }
            }
            if(receiver != null){
                try{
                    receiver.close();
                }catch(IOException e){
                    
                }
            }
            if(deconv_service_socket != null){
                try{
                    deconv_service_socket.close();
                }catch(IOException e){
                    
                }
            }
        }
        
    }
    
    /**
     * Converts a scaled current signal to the approximate logk value that may have generated it.
     * This serves as an inverse for {@link #logkToCurrent(double)}.
     * Newton's method is used to approximate this logk value.
     * @param scaled_current The scaled current as a value between 0 and 1.
     * @return the logk that will result in current when used as an argument for {@link #logkToCurrent(double)}.
     */
    static double currentToLogk(double scaled_current){
        double perturbation_logk = 0.01; //the perturbation to use when approximating the derivative for #logkToCurrent(double).
        double threshold = 0.005; //the threshold for determining convergence (differences in candidate logk that fall below this value will be considered converged).
        int iterations = 8; //number of iterations of Newton's method
        
        double candidate_logk = 0.5*(LOGK_HIGH - LOGK_LOW); //initial guess for logk (should be located in the sloped portion of the k-i curve).
        double candidate_i;
        double derivative;
        double old_candidate;
        
        do{
            old_candidate = candidate_logk;
            candidate_i = logkToCurrent(candidate_logk);
            derivative = (logkToCurrent(candidate_logk + perturbation_logk) - candidate_i)/ perturbation_logk;
            
            candidate_logk -= (candidate_i - scaled_current)/derivative;
            
            iterations --;
        }while(iterations > 0 && Math.abs(old_candidate - candidate_logk) > threshold);
        
        return candidate_logk;
    }
    
    /**
     * <p>Encodes a logk - current curve into a byte array for sending over a network connection.</p>
     * <p>Data is encoded according to the following format:</p>
     * <code><p>"len: %d\r\n"</p>
     * <p>[Binary data containing logks] + "\r\n"</p>
     * <p>[Binary data containing currents] + "\r\n"</p></code>
     * <p>Doubles are converted to bytes using {@link #ENDIANNESS} endianness</p>
     * <p></p>
     * @param logks a double array comprising the logk data
     * @param currents a double array comprising the current data
     * @return the logk - current encoded as a byte array
     */
    static byte[] encodeCurve(double[] logks, double[] currents){
        /*
        "len: %d\r\n", len
        [Binary data containing logks] + "\r\n"
        [Binary data containing currents] + "\r\n"
        */
        int len = logks.length;
        String first_line = String.format("len: %d\r\n", len);
        String crlf = "\r\n";
        
        byte[] first_line_data = first_line.getBytes(CHARSET);
        byte[] crlf_data = crlf.getBytes(CHARSET);
        byte[] logk_data = new byte[len*8];
        byte[] current_data = new byte[len*8];
        
        ByteBuffer logk_bb = ByteBuffer.wrap(logk_data).order(ENDIANNESS);
        ByteBuffer current_bb = ByteBuffer.wrap(current_data).order(ENDIANNESS);
        
        for(int i = 0; i < logks.length; i++){
            logk_bb.putDouble(i*8, logks[i]);
            current_bb.putDouble(i*8, currents[i]);
        }
        
        //Append the data together
        int block_length = first_line_data.length + logk_data.length + current_data.length + 2*crlf_data.length;
        byte[] block_data = new byte[block_length];
        int running_length = 0;
        System.arraycopy(first_line_data, 0, block_data, 0, first_line_data.length);
        running_length += first_line_data.length;
        System.arraycopy(logk_data, 0, block_data, running_length, logk_data.length);
        running_length += logk_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        running_length += crlf_data.length;
        System.arraycopy(current_data, 0, block_data, running_length, current_data.length);
        running_length += current_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        return block_data;
    }
    
    /**
     * <p>Encodes image data into a byte array for sending over a network connection.</p>
     * <p>Data is encoded according to the following format:</p>
     * <code><p>"xlen: %d\r\n"</p>
     * <p>"ylen: %d\r\n"</p>
     * <p>[Binary data containing xs] + "\r\n"</p>
     * <p>[Binary data containing ys] + "\r\n"</p>
     * <p>[Binary data containing signals] + "\r\n"</p></code>
     * <p>Doubles are converted to bytes using {@link #ENDIANNESS} endianness</p>
     * <p>The image signal data is mapped to one dimension as a series of scans in the y-direction i.e.:</p>
     * <code><p>for(x = 0 -> xlen)</p>
     * <p>  for(y = 0 -> ylen)</p>
     * <p>      Append signal[x][y] to byte array</p>
     * <p>  end for</p>
     * <p>end for</p></code>
     * <p></p>
     * @param xs a double array comprising the x coordinates of the pixels in the image
     * @param ys a double array comprising the y coordinates of the pixels in the image
     * @param signals a double array containing the signal data of the image. 
     * Indexed as signals[x][y]
     * @return the image data as a byte array
     */
    static byte[] encodeImage(double[] xs, double[] ys, double[][] signals){
        /*
        "xlen: %d\r\n", xlen
        "ylen: %d\r\n", ylen
        [Binary data containing xs] + "\r\n"
        [Binary data containing ys] + "\r\n"
        [Binary data containing signals] + "\r\n"
        */
        int xlen = xs.length;
        int ylen = ys.length;
        String size_lines = String.format("xlen: %d\r\nylen: %d\r\n", xlen, ylen);
        String crlf = "\r\n";
        
        byte[] size_line_data = size_lines.getBytes(CHARSET);
        byte[] crlf_data = crlf.getBytes(CHARSET);
        byte[] x_data = new byte[xlen*8];
        byte[] y_data = new byte[ylen*8];
        byte[] img_data = new byte[xlen*ylen*8];
        
        ByteBuffer x_bb = ByteBuffer.wrap(x_data).order(ENDIANNESS);
        ByteBuffer y_bb = ByteBuffer.wrap(y_data).order(ENDIANNESS);
        ByteBuffer img_bb = ByteBuffer.wrap(img_data).order(ENDIANNESS);
        
        for(int i = 0; i < xs.length; i++){
            x_bb.putDouble(i*8, xs[i]);
        }
        for(int i = 0; i < ys.length; i++){
            y_bb.putDouble(i*8, ys[i]);
        }
        for(int x = 0; x < xlen; x++){
            int xcontrib = x*ylen;
            for(int y = 0; y < ylen; y++){
                int indx = xcontrib + y;
                img_bb.putDouble(indx*8, signals[x][y]);
            }
        }
        
        //Append the data together
        int block_length = size_line_data.length + x_data.length + y_data.length + img_data.length + 3*crlf_data.length;
        byte[] block_data = new byte[block_length];
        int running_length = 0;
        System.arraycopy(size_line_data, 0, block_data, 0, size_line_data.length);
        running_length += size_line_data.length;
        System.arraycopy(x_data, 0, block_data, running_length, x_data.length);
        running_length += x_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        running_length += crlf_data.length;
        System.arraycopy(y_data, 0, block_data, running_length, y_data.length);
        running_length += y_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        running_length += crlf_data.length;
        System.arraycopy(img_data, 0, block_data, running_length, img_data.length);
        running_length += img_data.length;
        System.arraycopy(crlf_data, 0, block_data, running_length, crlf_data.length);
        return block_data;
    }
    
    /**
     * Overwrites {@link #FILE_PATH_DATA} to only contain on single "%".
     * @throws FileNotFoundException 
     */
    static void eraseDataFile() throws FileNotFoundException{
        File f = new File(FILE_PATH_DATA);
        PrintWriter pw = new PrintWriter(f);
        pw.print("%");
        pw.close();
    }
    
    /**
     * Generates a timestamp loosely following ISO 8601
     * @return 
     */
    static String getDateStamp(){
        Calendar cl = Calendar.getInstance();
        int year = cl.get(Calendar.YEAR);
        int month = cl.get(Calendar.MONTH) + 1;
        int day = cl.get(Calendar.DAY_OF_MONTH);
        int hour = cl.get(Calendar.HOUR_OF_DAY);
        int minute = cl.get(Calendar.MINUTE);
        int second = cl.get(Calendar.SECOND);
        String date_time = String.format("%04d-%02d-%02dT%02d:%02d:%02d", year, month, day, hour, minute, second);
        return date_time;
    }
    
    /**
     * Sends a HEAD request for <code>content_id</code> to the server and returns the ETag for the version of this content on file in the server.
     * @param sender the OutputStream for sending information to the server
     * @param receiver the InputStream for receiving information from the server
     * @param content_id the identity of the requested content. 
     * There are three pieces of content that can be sent back and forth between this program and the server:
     * <ul>
     * <li>k-curve</li>
     * <li>k-image</li>
     * <li>secm-image</li>
     * </ul>
     * @return returns the ETag for <code>content_id</code> if the content exists on the server, null otherwise.
     * @throws IOException occur when unexpected responses are received or the server sends a ststus that is not either <code>200 OK</code> or <code>404 Not found</code> 
     */
    static String getETag(OutputStream sender, InputStream receiver, String content_id) throws IOException{
        String CRLF = "\r\n";
        String requestline = "HEAD " + content_id + " HTTP/1.1";
        String fields = "Date: " + getDateStamp();
        //send head request
        String request_full = requestline + CRLF + fields + CRLF + CRLF;
        sender.write(request_full.getBytes(CHARSET));
        sender.flush(); // make sure everything gets sent
        
        //listen for response
        String response_status_line = "";
        
        int currentbyte = -1;
        int lastbyte = -1;
        boolean continueparsing = true;
        int characters = 0;
        
        while((currentbyte = receiver.read()) >= 0 && continueparsing && characters < MAX_NON_BODY_LENGTH){
            if(currentbyte == 10 && lastbyte == 13){
                continueparsing = false;
            }
            else{
                if(lastbyte >= 0){
                    response_status_line = response_status_line + (char)lastbyte;
                }
            }
            lastbyte = currentbyte;
            characters ++;
        }
        
        String[] status_line_tokens = response_status_line.split("\\s+");
        //If an incorrect status message is recieved, or an unexpected status is received, throw an error
        if(!status_line_tokens[0].equals("HTTP/1.1")){
            throw new IOException("Status line did not start with HTTP/1.1");
        }
        if(!status_line_tokens[1].equals("200") && !status_line_tokens[1].equals("404")){
            throw new IOException("Received unexpected status code. Expected: (200|404); Received: " + status_line_tokens[1]);
        }
        
        //read the rest of the message to get the ETag or clear the receiver.
        continueparsing = true;
        String etag = null;
        int chars_since_crlf = 0;//characters since a carriage-return line-feed
        characters = 0;
        String last_response_field_line = "";
        lastbyte = -1;
        while((currentbyte = receiver.read()) >= 0 && continueparsing && characters < MAX_NON_BODY_LENGTH){
            if(currentbyte == 10 && lastbyte == 13){
                if(chars_since_crlf == 1){
                    continueparsing = false;
                }
                chars_since_crlf = -1;
                if(last_response_field_line.startsWith("ETag: ")){
                    if(etag == null){
                        etag = last_response_field_line.substring(6).trim();
                    }
                    else{
                        throw new IOException("Encountered more than one ETag field.");
                    }
                }
                last_response_field_line = "";
            }
            else{
                if(lastbyte >= 0){
                    last_response_field_line = last_response_field_line + (char)lastbyte;
                }
            }
            lastbyte = currentbyte;
            characters ++;
            chars_since_crlf ++;
        }
        
        if(characters >= MAX_NON_BODY_LENGTH){
            throw new IOException("Response from server too long.");
        }
        
        //process the result
        return etag;
    }
    
    /**
     * Converts the y-data of a curve y = f(x) to a byte array and hashes it according to {@link #HASH_ALGORITHM}.
     * This is used for generating ETags to reduce the amount of times data is sent over the network.
     * The doubles in the curve data are converted to bytes with {@link #ENDIANNESS} endianness.
     * @param curve the curve data to be hashed.
     * @return the hash of the given curve after it has been converted to a byte array.
     */
    static byte[] hashCurve(double[] curve){
        //convert curve to byte array
        int len = 8*curve.length;
        byte[] bytearray = new byte[len];
        ByteBuffer bb = ByteBuffer.wrap(bytearray).order(ENDIANNESS);
        for(int i = 0; i < curve.length; i++){
            bb.putDouble(i*8, curve[i]);
        }
        //hash byte array
        MessageDigest sha256;
        try {
            sha256 = MessageDigest.getInstance(HASH_ALGORITHM);
            byte[] hash = sha256.digest(bytearray);
            return hash;
        } catch (NoSuchAlgorithmException ex) {
            
        }
        
        return new byte[0];
    }
    
    /**
     * Converts image data to a byte array and hashes it according to {@link #HASH_ALGORITHM}.
     * This is used for generating ETags to reduce the amount of times data is sent over the network.
     * The doubles in the image data are converted to bytes with {@link #ENDIANNESS} endianness.
     * The image data is mapped to one dimension as a series of scans in the y-direction i.e.:
     * <code><p>for(x = 0 -> xlen)</p>
     * <p>  for(y = 0 -> ylen)</p>
     * <p>      Append signal[x][y] to byte array</p>
     * <p>  end for</p>
     * <p>end for</p></code>
     * @param image the image data to be hashed
     * @return the hash of the given image after it has been mapped to one dimension and converted to a byte array.
     */
    static byte[] hashImage(double[][] image){
        //convert image to byte array
        int xlen = image.length;
        int ylen = image[0].length;
        int total_len = xlen*ylen*8;
        byte[] bytearray = new byte[total_len];
        ByteBuffer bb = ByteBuffer.wrap(bytearray).order(ENDIANNESS);
        for(int x = 0; x < xlen; x++){
            int xcontrib = x*ylen;
            for(int y = 0; y < ylen; y++){
                int indx = xcontrib + y;
                bb.putDouble(indx*8, image[x][y]);
            }
        }
        //hash byte array
        MessageDigest sha256;
        try {
            sha256 = MessageDigest.getInstance(HASH_ALGORITHM);
            byte[] hash = sha256.digest(bytearray);
            return hash;
        } catch (NoSuchAlgorithmException ex) {
            
        }
        
        return new byte[0];
    }
    
    /**
     * Converts the byte arrays from {@link #hashCurve(double[])} or {@link #hashImage(double[][])} to a string containing the hexadecimal representation of the hash.
     * @param hash the hash to be converted to a hexadecimal string
     * @return the String representation of the hash
     */
    static String hashToString(byte[] hash){
        String hash_string = "";
        for(int i = 0; i < hash.length; i++){
            hash_string = hash_string + String.format("%02x", hash[i]);
        }
        return hash_string;
    }
    
    /**
     * Converts a logk for a spot at the surface to a scaled current that would 
     * be observed by a microelectrode above the surface.This function is inverted
     * by {@link #currentToLogk(double)}.
     * @param logk The log rate constant
     * @return 
     */
    static double logkToCurrent(double logk){
        return 1;
    }
    
    /**
     * Sends a post-processing request to the server, sending along an SECM Image and awaiting a new k image to simulate.
     * The server should either send 
     * <ul>
     * <li>A "200 OK" response with a new k image. In which case this function decodes the k image and writes new values to {@link #img_x_coordinates}, {@link #img_y_coordinates} and {@link #img_ks}.</li>
     * <li>A "204 No Content" response indicating convergence. In which case this function sets {@link #img_x_coordinates}, {@link #img_y_coordinates} and {@link #img_ks} to null.</li>
     * <li>Any other code indicating an error has occurred. In which case an IOException is thrown</li>
     * </ul>
     * 
     * @param sender the OutputStream to the server.
     * @param receiver the InputStream from the server.
     * @param xs the x-coordinates for the current image.
     * @param ys the y-coordinates for the current image.
     * @param currentimg the current image. Indexed as <code>currentimg[x][y]</code>.
     * @throws IOException Thrown when networking errors occur or an unexpected response is received from the server.
     */
    static void postSecmImage(OutputStream sender, InputStream receiver, double[] xs, double[] ys, double[][] currentimg) throws IOException{
        //POST SECM Image
        String etag = hashToString(hashImage(currentimg));
        byte[] image_data = encodeImage(xs, ys, currentimg);
        int content_length = image_data.length;
        String post_header = "POST secm-image HTTP/1.1\r\n"
                + "Date: " + getDateStamp() + "\r\n"
                + "ETag: " + etag + "\r\n"
                + "Content-Length: " + content_length + "\r\n"
                + "Content-Type: IMAGE\r\n"
                + "\r\n";
        sender.write(post_header.getBytes(CHARSET));
        sender.write(image_data);
        sender.flush();
        
        //listen for response
        String response_status_line = "";
        
        int currentbyte = -1;
        int lastbyte = -1;
        boolean continueparsing = true;
        int characters = 0;
        
        while((currentbyte = receiver.read()) >= 0 && continueparsing && characters < MAX_NON_BODY_LENGTH){
            if(currentbyte == 10 && lastbyte == 13){
                continueparsing = false;
            }
            else{
                if(lastbyte >= 0){
                    response_status_line = response_status_line + (char)lastbyte;
                }
            }
            lastbyte = currentbyte;
            characters ++;
        }
        
        String[] status_line_tokens = response_status_line.split("\\s+");
        //If an incorrect status message is recieved, or an unexpected status is received, throw an error
        if(!status_line_tokens[0].equals("HTTP/1.1")){
            throw new IOException("Status line did not start with HTTP/1.1");
        }
        
        if(!status_line_tokens[1].equals("200") || !status_line_tokens[1].equals("204")){
            throw new IOException("Received unexpected status code. Expected: 200; Received: " + status_line_tokens[1]);
        }
        else if(status_line_tokens[1].equals("204")){
            img_x_coordinates = null;
            img_y_coordinates = null;
            img_ks = null;
            return;
        }
        
        //read the rest of the message to get the ETag or clear the receiver.
        continueparsing = true;
        String field_content_length = null;
        int chars_since_crlf = 0;//characters since a carriage-return line-feed
        characters = 0;
        String last_response_field_line = "";
        lastbyte = -1;
        while((currentbyte = receiver.read()) >= 0 && continueparsing && characters < MAX_NON_BODY_LENGTH){
            if(currentbyte == 10 && lastbyte == 13){
                if(chars_since_crlf == 1){
                    continueparsing = false;
                }
                chars_since_crlf = -1;
                if(last_response_field_line.startsWith("Content-Length: ")){
                    if(field_content_length == null){
                        field_content_length = last_response_field_line.substring(6).trim();
                    }
                    else{
                        throw new IOException("Response header to POST contained more than one Content-Length field.");
                    }
                }
                last_response_field_line = "";
            }
            else{
                if(lastbyte >= 0){
                    last_response_field_line = last_response_field_line + (char)lastbyte;
                }
            }
            lastbyte = currentbyte;
            characters ++;
            chars_since_crlf ++;
        }
        
        if(characters >= MAX_NON_BODY_LENGTH){
            throw new IOException("Response header to POST from server too long.");
        }
        
        if(field_content_length == null){
            throw new IOException("Response to POST request did not contain content.");
        }
        
        int bytesleft = Integer.parseInt(field_content_length);
        lastbyte = -1;
        continueparsing = true;
        String line_xlen = "";
        while((currentbyte = receiver.read()) >= 0 && bytesleft > 0 && continueparsing){
            if(currentbyte == 10 && lastbyte == 13){
                continueparsing = false;
            }
            else{
                if(lastbyte >= 0){
                    line_xlen = line_xlen + (char)lastbyte;
                }
            }
            lastbyte = currentbyte;
            bytesleft --;
        }
        lastbyte = -1;
        continueparsing = true;
        String line_ylen = "";
        while((currentbyte = receiver.read()) >= 0 && bytesleft > 0 && continueparsing){
            if(currentbyte == 10 && lastbyte == 13){
                continueparsing = false;
            }
            else{
                if(lastbyte >= 0){
                    line_ylen = line_ylen + (char)lastbyte;
                }
            }
            lastbyte = currentbyte;
            bytesleft --;
        }
        int xlen = Integer.parseInt(line_xlen.substring(6).trim());
        int ylen = Integer.parseInt(line_ylen.substring(6).trim());
        int imglen = xlen*ylen;
        int expect_cr_13 = 0;
        int expect_lf_10 = 0;
        
        //read x-data line
        int xind = 0;
        int xlen_bytes = xlen*8;
        byte[] x_data_bytes = new byte[xlen_bytes];
        while((currentbyte = receiver.read()) >= 0 && bytesleft > 0 && xind < xlen_bytes){
            x_data_bytes[xind] = (byte)(currentbyte & 0xFF);
            bytesleft--;
            xind++;
        }
        //read the carriage return and line feed after 
        if(currentbyte < 0 || xind < xlen_bytes){
            throw new IOException("Hit end of message before x-data ended.");
        }
        currentbyte = receiver.read();
        bytesleft--;
        if(currentbyte >=0){
            expect_cr_13 = currentbyte;
        }
        else{
            throw new IOException("Hit end of message before x-data ended.");
        }
        currentbyte = receiver.read();
        bytesleft--;
        if(currentbyte >=0){
            expect_lf_10 = currentbyte;
        }
        else{
            throw new IOException("Hit end of message before x-data ended.");
        }
        //make sure expected x-data is terminated with a CRLF
        if(expect_cr_13 != 13 || expect_lf_10 != 10){
            throw new IOException("Carriage-return Line-feed absent at end of x-data.");
        }
        
        //read y-data line
        int yind = 0;
        int ylen_bytes = ylen*8;
        byte[] y_data_bytes = new byte[ylen_bytes];
        while((currentbyte = receiver.read()) >= 0 && bytesleft > 0 && yind < ylen_bytes){
            y_data_bytes[yind] = (byte)(currentbyte & 0xFF);
            bytesleft--;
            yind++;
        }
        //read the carriage return and line feed after 
        if(currentbyte < 0 || yind < ylen_bytes){
            throw new IOException("Hit end of message before y-data ended.");
        }
        currentbyte = receiver.read();
        bytesleft--;
        if(currentbyte >=0){
            expect_cr_13 = currentbyte;
        }
        else{
            throw new IOException("Hit end of message before y-data ended.");
        }
        currentbyte = receiver.read();
        bytesleft--;
        if(currentbyte >=0){
            expect_lf_10 = currentbyte;
        }
        else{
            throw new IOException("Hit end of message before y-data ended.");
        }
        //make sure expected x-data is terminated with a CRLF
        if(expect_cr_13 != 13 || expect_lf_10 != 10){
            throw new IOException("Carriage-return Line-feed absent at end of y-data.");
        }
        
        //read image-data line
        int imgind = 0;
        int imglen_bytes = imglen*8;
        byte[] img_data_bytes = new byte[imglen_bytes];
        while((currentbyte = receiver.read()) >= 0 && bytesleft > 0 && imgind < imglen_bytes){
            img_data_bytes[imgind] = (byte)(currentbyte & 0xFF);
            bytesleft--;
            imgind++;
        }
        //read the carriage return and line feed after 
        if(currentbyte < 0 || imgind < imglen_bytes){
            throw new IOException("Hit end of message before image-data ended.");
        }
        currentbyte = receiver.read();
        bytesleft--;
        if(currentbyte >=0){
            expect_cr_13 = currentbyte;
        }
        else{
            throw new IOException("Hit end of message before image-data ended.");
        }
        currentbyte = receiver.read();
        bytesleft--;
        if(currentbyte >=0){
            expect_lf_10 = currentbyte;
        }
        else{
            throw new IOException("Hit end of message before image-data ended.");
        }
        //make sure expected x-data is terminated with a CRLF
        if(expect_cr_13 != 13 || expect_lf_10 != 10){
            throw new IOException("Carriage-return Line-feed absent at end of image-data.");
        }
        
        //convert byte arrays to doubles.
        ByteBuffer x_bb = ByteBuffer.wrap(x_data_bytes).order(ENDIANNESS);
        ByteBuffer y_bb = ByteBuffer.wrap(y_data_bytes).order(ENDIANNESS);
        ByteBuffer img_bb = ByteBuffer.wrap(img_data_bytes).order(ENDIANNESS);
        
        img_x_coordinates = new double[xlen];
        img_y_coordinates = new double[ylen];
        img_ks = new double[xlen][ylen];
        
        for(int x = 0; x < xlen; x++){
            int xcontrib = x*ylen;
            img_x_coordinates[x] = x_bb.getDouble(x*8);
            for(int y = 0; y < ylen; y++){
                int indx = (xcontrib + y)*8;
                img_ks[x][y] = img_bb.getDouble(indx);
            }
        }
        
        for(int y= 0; y < ylen; y++){
            img_y_coordinates[y] = y_bb.getDouble(y*8);
        }
    }
    
    /**
     * Reads the response to PUT requests from the server, ensuring that the data was received correctly. 
     * This serves to clear the server response from the InputStream and take no further action if everything operates correctly.
     * If an incorrect response is received, an IOException will be thrown to halt this program.
     * @param receiver The InputStream from the server.
     * @throws IOException To be thrown if there are any errors that occur on the server side or in the case of an incorrect response from the server.
     */
    static void processPutResponse(InputStream receiver) throws IOException{
        //listen for response
        String response_status_line = "";
        
        int currentbyte = -1;
        int lastbyte = -1;
        boolean continueparsing = true;
        int characters = 0;
        
        while((currentbyte = receiver.read()) >= 0 && continueparsing && characters < MAX_NON_BODY_LENGTH){
            if(currentbyte == 10 && lastbyte == 13){
                continueparsing = false;
            }
            else{
                if(lastbyte >= 0){
                    response_status_line = response_status_line + (char)lastbyte;
                }
            }
            lastbyte = currentbyte;
            characters ++;
        }
        
        String[] status_line_tokens = response_status_line.split("\\s+");
        //If an incorrect status message is recieved, or an unexpected status is received, throw an error
        if(!status_line_tokens[0].equals("HTTP/1.1")){
            throw new IOException("Status line did not start with HTTP/1.1");
        }
        if(!status_line_tokens[1].equals("200")){
            throw new IOException("Received unexpected status code to PUT request. Expected: 200; Received: " + status_line_tokens[1]);
        }
        
        continueparsing = true;
        int chars_since_crlf = 0;//characters since a carriage-return line-feed
        characters = 0;
        lastbyte = -1;
        while((currentbyte = receiver.read()) >= 0 && continueparsing && characters < MAX_NON_BODY_LENGTH){
            if(currentbyte == 10 && lastbyte == 13){
                if(chars_since_crlf == 1){
                    continueparsing = false;
                }
                chars_since_crlf = -1;
            }
            lastbyte = currentbyte;
            characters ++;
            chars_since_crlf ++;
        }
        
        if(characters >= MAX_NON_BODY_LENGTH){
            throw new IOException("Response from server too long.");
        }
    }
    
    /**
     * Handles the process of sending a PUT request for the k-curve to the server.
     * This starts by calling {@link #getETag(java.io.OutputStream, java.io.InputStream, java.lang.String)} to check the copy of the k-curve on the server by making a HEAD request and comparing the ETag to the hash of the k-curve.
     * If the ETag and hash match, the server is up-to-date and the data is not sent over.
     * If the ETag does not match or a 404 Not Found response is received, a PUT request is made, sending the k-curve data on to the server.
     * {@link #processPutResponse(java.io.InputStream)} is used to ensure the server received the data correctly.
     * @param sender The OutputStream to the server.
     * @param receiver The InputStream from the server.
     * @param logks The logk data. Must have the same size as <code>currents</code>
     * @param currents The current data. Must have the same size as <code>logks</code>
     * @throws IOException Will be thrown if there are any errors when contacting the server or if an unexpected response is received.
     * @see #getETag(java.io.OutputStream, java.io.InputStream, java.lang.String) 
     */
    static void putKCurve(OutputStream sender, InputStream receiver, double[] logks, double[] currents) throws IOException{
        /*
        HEAD kcurve
            if 200 OK received compare recieved hash to curve's hash
            if 204 No Content received OR the hashes do not match, send kurve data over
        */
        //HEAD kcurve
        String etag_new = hashToString(hashCurve(currents));
        String etag_cached = getETag(sender, receiver, "k-curve");
        //if 200 OK received compare recieved hash to curve's hash
        //if 404 Not Found received OR the hashes do not match, send kurve data over
        boolean send_curve = true;
        if(etag_cached != null){
            send_curve = !etag_cached.equals(etag_new);
        }
        if(send_curve){
            byte[] curve_data = encodeCurve(logks, currents);
            int content_length = curve_data.length;
            String put_header = "PUT k-curve HTTP/1.1\r\n" 
                    + "Date: " + getDateStamp() + "\r\n"
                    + "ETag: " + etag_new + "\r\n"
                    + "Content-Length: " + content_length + "\r\n"
                    + "Content-Type: IMAGE\r\n"
                    + "\r\n";
            sender.write(put_header.getBytes(CHARSET));
            sender.write(curve_data);
            sender.flush();
            
            processPutResponse(receiver);
        }
    }
    
    /**
     * Handles the process of sending a PUT request for the k-image to the server.
     * This starts by calling {@link #getETag(java.io.OutputStream, java.io.InputStream, java.lang.String)} to check the copy of the k-image on the server by making a HEAD request and comparing the ETag to the hash of the k-image.
     * If the ETag and hash match, the server is up-to-date and the data is not sent over.
     * If the ETag does not match or a 404 Not Found response is received, a PUT request is made, sending the k-image data on to the server.
     * {@link #processPutResponse(java.io.InputStream)} is used to ensure the server received the data correctly.
     * @param sender The OutputStream to the server.
     * @param receiver The InputStream from the server.
     * @param xs The x position data. Indexed as <code>xs[x]</code>.
     * @param ys The y position data. Indexed as <code>ys[y]</code>.
     * @param logkimg The k-image data. Indexed as <code>logkimg[x][y]</code>.
     * @throws IOException Will be thrown if there are any errors when contacting the server or if an unexpected response is received.
     */
    static void putKImage(OutputStream sender, InputStream receiver, double[] xs, double[] ys, double[][] logkimg) throws IOException{
        /*
        HEAD image
            if 200 OK received compare recieved hash to image's hash
            if 204 No Content received OR the hashes do not match, send kurve data over
        */
        //HEAD image
        String etag_new = hashToString(hashImage(logkimg));
        String etag_cached = getETag(sender, receiver, "k-image");
        //if 200 OK received compare recieved hash to curve's hash
        //if 404 Not Found received OR the hashes do not match, send kurve data over
        boolean send_image = true;
        if(etag_cached != null){
            send_image = !etag_cached.equals(etag_new);
        }
        if(send_image){
            byte[] image_data = encodeImage(xs, ys, logkimg);
            int content_length = image_data.length;
            String put_header = "PUT k-image HTTP/1.1\r\n" 
                    + "Date: " + getDateStamp() + "\r\n"
                    + "ETag: " + etag_new + "\r\n"
                    + "Content-Length: " + content_length + "\r\n"
                    + "Content-Type: IMAGE\r\n"
                    + "\r\n";
            sender.write(put_header.getBytes(CHARSET));
            sender.write(image_data);
            sender.flush();
            
            processPutResponse(receiver);
        }
    }
    
    /**
     * Handles the process of sending a PUT request for the k-image to the server.
     * This starts by calling {@link #getETag(java.io.OutputStream, java.io.InputStream, java.lang.String)} to check the copy of the k-image on the server by making a HEAD request and comparing the ETag to the hash of the k-image.
     * If the ETag and hash match, the server is up-to-date and the data is not sent over.
     * If the ETag does not match or a 404 Not Found response is received, a PUT request is made, sending the k-image data on to the server.
     * {@link #processPutResponse(java.io.InputStream)} is used to ensure the server received the data correctly.
     * @param sender The OutputStream to the server.
     * @param receiver The InputStream from the server.
     * @param xs The x position data. Indexed as <code>xs[x]</code>.
     * @param ys The y position data. Indexed as <code>ys[y]</code>.
     * @param trueimg The true secm image data. Indexed as <code>trueimg[x][y]</code>.
     * @throws IOException Will be thrown if there are any errors when contacting the server or if an unexpected response is received.
     */
    static void putTrueSecmImage(OutputStream sender, InputStream receiver, double[] xs, double[] ys, double[][] trueimg) throws IOException{
        /*
        HEAD image
            if 200 OK received compare recieved hash to image's hash
            if 204 No Content received OR the hashes do not match, send kurve data over
        */
        //HEAD image
        String etag_new = hashToString(hashImage(trueimg));
        String etag_cached = getETag(sender, receiver, "true-image");
        //if 200 OK received compare recieved hash to curve's hash
        //if 404 Not Found received OR the hashes do not match, send kurve data over
        boolean send_image = true;
        if(etag_cached != null){
            send_image = !etag_cached.equals(etag_new);
        }
        if(send_image){
            byte[] image_data = encodeImage(xs, ys, trueimg);
            int content_length = image_data.length;
            String put_header = "PUT true-image HTTP/1.1\r\n" 
                    + "Date: " + getDateStamp() + "\r\n"
                    + "ETag: " + etag_new + "\r\n"
                    + "Content-Length: " + content_length + "\r\n"
                    + "Content-Type: IMAGE\r\n"
                    + "\r\n";
            sender.write(put_header.getBytes(CHARSET));
            sender.write(image_data);
            sender.flush();
            
            processPutResponse(receiver);
        }
    }
    
    /**
     * Reads from the rightmost column of {@link #FILE_PATH_DATA} and returns the result as an array of doubles
     * @return 
     * @throws FileNotFoundException 
     */
    static double[] readData() throws FileNotFoundException{
        File f = new File(FILE_PATH_DATA);
        Scanner s = new Scanner(f);
        int count = 0;
        while(s.hasNextLine()){
            String ln = s.nextLine();
            if(!ln.startsWith("%")){
                count ++;
            }
        }
        s.close();
        double[] data = new double[count];
        s = new Scanner(f);
        count = 0;
        while(s.hasNextLine()){
            String ln = s.nextLine();
            if(!ln.startsWith("%")){
                String[] linedata = ln.trim().split("\\s+");// split whilespace separated columns
                data[count] = Double.parseDouble(linedata[linedata.length -1]);//read from the rightmost column
                count ++;
            }
        }
        s.close();
        return data;
    }
    
    /**
     * Handles the simulation and data processing that will be used by {@link #logkToCurrent(double)} to convert rate constants to currents.
     * @param L The normalized tip to substrate distance.
     */
    static void simulateKCurve(double L, boolean verbose) throws IOException{
        double[] xspace = new double[]{0, 200, 400};
        double[] yspace = new double[]{0, 200, 400};
        double[][] grid_data = new double[][]{{1, 1, 1},
            {1, 1, 1},
            {1, 1, 1}};
        
        double amplitude = LOGK_HIGH - LOGK_LOW;
        int k_datapoints = (int)amplitude;
        double[] logk_data = new double[k_datapoints];
        double[] k_data = new double[k_datapoints];
        for(int i = 0; i < k_datapoints; i++){
            double mult = ((double)i)/((double)k_datapoints);
            logk_data[i] = mult*amplitude + LOGK_LOW;
            k_data[i] = Math.pow(10, logk_data[i]);
        }
        
        writeReactivityFile(xspace, yspace, grid_data);
        Model model = runk(L, xspace[1], yspace[1], k_data);
        
        double[] ki_currents = readData();
        eraseDataFile();
        ki_logks = new double[k_datapoints];
        System.arraycopy(k_data, 0, ki_logks, 0, k_datapoints);
        
        if(verbose){
            writeKCurve(k_data, ki_currents);
        }
    }
    
    /**
     * Writes k-curve data to {@link #FILE_PATH_KLOG} in a comma separated values (csv) format.
     * @param k_data The logk data. Must have the same size as <code>currents</code>
     * @param currents The current data. Must have the same size as <code>k_data</code>
     * @throws IOException If the {@link #FILE_PATH_KLOG} cannot be created or written to.
     */
    static void writeKCurve(double[] k_data, double[] currents) throws IOException{
        File f = new File(FILE_PATH_KLOG);
        f.createNewFile();
        PrintWriter pw = new PrintWriter(f);
        pw.print("#log10(k/1[m/s]), i[A]");
        for(int i = 0; i < k_data.length; i++){
            pw.print(String.format("\n%f,%f", k_data[i], currents[i]));
        }
        pw.close();
    }
    
    /**
     * Writes the reactivity map to a file that is read by the COMSOL simulation.
     * {@link #FILE_PATH_REACTIVITY} controls where this data is written
     * @param xs The x position data. Indexed as <code>xs[x]</code>.
     * @param ys The y position data. Indexed as <code>ys[y]</code>.
     * @param logks The k-image data. Indexed as <code>logks[x][y]</code>.
     * @throws IOException If the {@link #FILE_PATH_KLOG} cannot be created or written to.
     */
    static void writeReactivityFile(double[] xs, double[] ys, double[][] logks) throws IOException{
        File f = new File(FILE_PATH_REACTIVITY);
        f.createNewFile();
        PrintWriter pw = new PrintWriter(new BufferedWriter(new FileWriter(f)));
        for(int x = 0; x < xs.length; x++){
            for(int y = 0; y < ys.length; y++){
                double k = Math.pow(10, logks[x][y]);
                if(x != 0 || y != 0){
                    pw.print("\n" + xs[x] + "," + ys[y] + "," + k);
                }
                else{
                    pw.print(xs[x] + "," + ys[y] + "," + k);
                }
            }
        }
        pw.close();
    }
    
    /**
     * Holds the currents from the logk-i curve.
     */
    static double[] ki_currents;
    
    /**
     * Holds the logk data from the logk-i curve.
     */
    static double[] ki_logks;
    
    /**
     * Holds the image data for the k-image. Indexed as <code>img_ks[x][y]</code>.
     */
    static double[][] img_ks;
    
    /**
     * Holds the x-data for the k-image. Indexed as <code>img_x_coordinates[x]</code>.
     */
    static double[] img_x_coordinates;
    
    /**
     * Holds the y-data for the k-image. Indexed as <code>img_y_coordinates[y]</code>.
     */
    static double[] img_y_coordinates;
    
    /**
     * The Charset to be used when sending messages to and from the server.
     */
    static final Charset CHARSET = Charset.forName("US-ASCII");
    
    /**
     * The ByteOrder to be used when encoding and decoding double to and from byte[]
     */
    static final ByteOrder ENDIANNESS = ByteOrder.LITTLE_ENDIAN;
    
    /**
     * The file path for COMSOL's data output file
     */
    static final String FILE_PATH_DATA = "data.txt";
    
    /**
     * The file path to which the logk-i curve will be written
     */
    static final String FILE_PATH_KLOG = "kcurve.csv";
    
    /**
     * The file path to which  the k-image that COMSOL will use is to be written.
     */
    static final String FILE_PATH_REACTIVITY = "func.csv";
    
    /**
     * The hashing algorithm to be used when generating ETags.
     * @see java.security.MessageDigest#getInstance(java.lang.String) 
     */
    static final String HASH_ALGORITHM = "SHA-256";
    
    /**
     * The host name for communicating with the deconvolution service server.
     * Set to null (the for loopback)
     */
    static final String HOST = null;
    
    /**
     * The logk value above which no change in current is expected
     */
    static final double LOGK_HIGH = -2;
    
    /**
     * The logk value below which no change in current is expected
     */
    static final double LOGK_LOW = -6;
    
    /**
     * The maximum length of the status line or the fields in HTTP message headers
     */
    static final int MAX_NON_BODY_LENGTH = 4000;
    
    /**
     * The port to use for communicating with the deconvolution service server.
     */
    static final int PORT = 4091;
}

class Model{
    
}
